window.AI_TOOLS_PRODUCTS = [
  {
    "productId": "chatgpt-plus",
    "sku": "ATP-CHATGPT-PLUS",
    "name": "ChatGPT Plus",
    "sourceProductTitle": "ChatGPT Plus",
    "slug": "chatgpt-plus",
    "category": "AI Assistants",
    "planTier": "Plus plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Advanced AI assistant",
    "keyFeatures": "Writing; research; coding help; brainstorming",
    "shortDescription": "All-round AI assistant for writing, study, coding and business work.",
    "fullDescription": "ChatGPT Plus is useful for students, freelancers and teams that need one flexible assistant for daily writing, research, coding support and planning.",
    "basePricePkr": 1833,
    "sellingPricePkr": 2200,
    "compareAtPricePkr": 3000,
    "discountPercent": 20,
    "imageUrl": "/assets/product-icons/chatgpt-plus.png",
    "imageAltText": "ChatGPT Plus subscription plan available in Pakistan",
    "sourceProductUrl": "https://chatgpt.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "CP",
    "guideUrl": "chatgpt-plus-pakistan/"
  },
  {
    "productId": "claude-ai",
    "sku": "ATP-CLAUDE-AI",
    "name": "Claude Pro",
    "sourceProductTitle": "Claude Pro",
    "slug": "claude-ai",
    "category": "Development and Coding",
    "planTier": "AI assistant plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Writing and coding assistant",
    "keyFeatures": "Long writing; research; code review; summaries",
    "shortDescription": "Careful AI assistant for long writing, research and coding support.",
    "fullDescription": "Claude AI is suitable for students, writers and developers who need structured output, careful rewriting, long-document help and code explanation.",
    "basePricePkr": 4583,
    "sellingPricePkr": 5500,
    "compareAtPricePkr": 7000,
    "discountPercent": 21,
    "imageUrl": "/assets/product-icons/claude-ai.png",
    "imageAltText": "Claude Pro subscription plan available in Pakistan",
    "sourceProductUrl": "https://claude.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "CP",
    "guideUrl": "claude-pro-pakistan/"
  },
  {
    "productId": "gemini-pro",
    "sku": "ATP-GEMINI-PRO",
    "name": "Gemini Pro",
    "sourceProductTitle": "Gemini Advanced",
    "slug": "gemini-pro",
    "category": "AI Assistants",
    "planTier": "Pro plan",
    "subscriptionDuration": "18 months",
    "durationMonths": 18,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Google AI access",
    "keyFeatures": "Google AI; writing; productivity; research",
    "shortDescription": "Google AI assistant access with long duration plan details.",
    "fullDescription": "Gemini Pro is listed for buyers who want Google AI access with PKR pricing, private access notes and WhatsApp order support in Pakistan.",
    "basePricePkr": 750,
    "sellingPricePkr": 900,
    "compareAtPricePkr": 1500,
    "discountPercent": 28,
    "imageUrl": "/assets/product-icons/gemini-pro.png",
    "imageAltText": "Gemini Pro subscription plan available in Pakistan",
    "sourceProductUrl": "https://gemini.google.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "GP",
    "guideUrl": "gemini-pro-pakistan/"
  },
  {
    "productId": "elevenlabs-creator-private",
    "sku": "ATP-ELEVENLABS-CREATOR",
    "name": "ElevenLabs Creator - Private",
    "sourceProductTitle": "ElevenLabs Creator",
    "slug": "elevenlabs-creator-private",
    "category": "AI Voice",
    "planTier": "Creator plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "300K+ credits",
    "keyFeatures": "AI voice; narration; dubbing; speech",
    "shortDescription": "AI voice subscription for narration, dubbing and creator audio workflows.",
    "fullDescription": "ElevenLabs Creator is useful for Pakistani creators who need AI voice generation, narration, dubbing and speech content with clear credit limits.",
    "basePricePkr": 2750,
    "sellingPricePkr": 3300,
    "compareAtPricePkr": 3600,
    "discountPercent": 8,
    "imageUrl": "/assets/product-icons/elevenlabs-creator-private.png",
    "imageAltText": "ElevenLabs Creator subscription plan available in Pakistan",
    "sourceProductUrl": "https://elevenlabs.io",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "EC",
    "guideUrl": "elevenlabs-creator-pakistan/"
  },
  {
    "productId": "runway-ml-unlimited-generations",
    "sku": "ATP-RUNWAY-ML",
    "name": "Runway ML - Unlimited Generations",
    "sourceProductTitle": "Runway ML",
    "slug": "runway-ml-unlimited-generations",
    "category": "AI Video",
    "planTier": "Video generation plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Video generation tools",
    "keyFeatures": "AI video; generation; editing; creative workflow",
    "shortDescription": "AI video generation access for creator and agency workflows.",
    "fullDescription": "Runway ML is listed for AI video generation buyers who need to confirm access type, delivery process, limits and PKR price before ordering.",
    "basePricePkr": 2100,
    "sellingPricePkr": 2520,
    "compareAtPricePkr": 3000,
    "discountPercent": 16,
    "imageUrl": "/assets/product-icons/runway-ml-unlimited-generations.png",
    "imageAltText": "Runway ML subscription plan available in Pakistan",
    "sourceProductUrl": "https://runwayml.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "RM",
    "guideUrl": "runway-ml-pakistan/"
  },
  {
    "productId": "leonardo-ai",
    "sku": "ATP-LEONARDO-AI",
    "name": "Leonardo AI",
    "sourceProductTitle": "Leonardo AI",
    "slug": "leonardo-ai",
    "category": "AI Images and Design",
    "planTier": "Design plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Image generation tools",
    "keyFeatures": "AI images; design; creative assets; prompts",
    "shortDescription": "AI image and design subscription for creative visual workflows.",
    "fullDescription": "Leonardo AI helps designers and content creators make AI images, creative assets and visual experiments with clear access and pricing checks.",
    "basePricePkr": 1000,
    "sellingPricePkr": 1200,
    "compareAtPricePkr": 1500,
    "discountPercent": 20,
    "imageUrl": "/assets/product-icons/leonardo-ai.png",
    "imageAltText": "Leonardo AI subscription plan available in Pakistan",
    "sourceProductUrl": "https://leonardo.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "LA",
    "guideUrl": "leonardo-ai-pakistan/"
  },
  {
    "productId": "grammarly-pro",
    "sku": "ATP-GRAMMARLY-PRO",
    "name": "Grammarly Premium",
    "sourceProductTitle": "Grammarly Premium",
    "slug": "grammarly-pro",
    "category": "Writing and SEO",
    "planTier": "Premium plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Grammar and writing tools",
    "keyFeatures": "Grammar; rewriting; proofreading; writing clarity",
    "shortDescription": "Writing assistant for grammar, rewriting and clarity checks.",
    "fullDescription": "Grammarly Premium is useful for students, writers and freelancers who want grammar checking, proofreading, rewriting suggestions and clearer English output.",
    "basePricePkr": 833,
    "sellingPricePkr": 1000,
    "compareAtPricePkr": 1200,
    "discountPercent": 17,
    "imageUrl": "/assets/product-icons/grammarly-pro.png",
    "imageAltText": "Grammarly Pro subscription plan available in Pakistan",
    "sourceProductUrl": "https://grammarly.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "GP",
    "guideUrl": "grammarly-premium-pakistan/"
  },
  {
    "productId": "quillbot",
    "sku": "ATP-QUILLBOT",
    "name": "QuillBot",
    "sourceProductTitle": "QuillBot",
    "slug": "quillbot",
    "category": "Writing and SEO",
    "planTier": "Writing plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Paraphrasing and writing tools",
    "keyFeatures": "Paraphrasing; summarizing; grammar; writing workflow",
    "shortDescription": "Paraphrasing and writing support for students and freelancers.",
    "fullDescription": "QuillBot helps with paraphrasing, rewriting, summaries and grammar workflows for buyers who need affordable writing support.",
    "basePricePkr": 399,
    "sellingPricePkr": 479,
    "compareAtPricePkr": 700,
    "discountPercent": 31,
    "imageUrl": "/assets/product-icons/quillbot.png",
    "imageAltText": "QuillBot subscription plan available in Pakistan",
    "sourceProductUrl": "https://quillbot.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "Q",
    "guideUrl": "quillbot-premium-pakistan/"
  },
  {
    "productId": "lovable-ai-pro-private",
    "sku": "ATP-LOVABLE-AI-PRO",
    "name": "Lovable AI Pro - Private",
    "sourceProductTitle": "Lovable AI Pro",
    "slug": "lovable-ai-pro-private",
    "category": "Development and Coding",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "100–300 credits",
    "keyFeatures": "AI coding; app building; prototyping; development",
    "shortDescription": "AI coding and app-building subscription for fast prototypes.",
    "fullDescription": "Lovable AI Pro is useful for builders and developers who want AI-assisted app creation, prototyping and coding workflow support.",
    "basePricePkr": 1250,
    "sellingPricePkr": 1500,
    "compareAtPricePkr": 2000,
    "discountPercent": 25,
    "plans": [
      {"label": "100 Credits", "price": 1500},
      {"label": "200 Credits", "price": 2000},
      {"label": "300 Credits", "price": 2500}
    ],
    "imageUrl": "/assets/product-icons/lovable-ai-pro-private.png",
    "imageAltText": "Lovable AI Pro subscription plan available in Pakistan",
    "sourceProductUrl": "https://lovable.dev",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "LA",
    "guideUrl": "lovable-ai-pro-pakistan/"
  },
  {
    "productId": "heygen-ai",
    "sku": "ATP-HEYGEN-AI",
    "name": "HeyGen AI",
    "sourceProductTitle": "HeyGen AI",
    "slug": "heygen-ai",
    "category": "AI Video",
    "planTier": "Creator / Pro / Pro Plus",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "600–2000 credits",
    "keyFeatures": "AI avatars; text to video; presentations; creator video",
    "shortDescription": "AI avatar and text-to-video tool for creator workflows.",
    "fullDescription": "HeyGen AI is listed for buyers who need avatar videos, text-to-video workflows and creator-friendly video production support.",
    "basePricePkr": 6167,
    "sellingPricePkr": 7400,
    "compareAtPricePkr": 10000,
    "discountPercent": 26,
    "plans": [
      {"label": "Creator (600 credits)", "price": 7400},
      {"label": "Pro (1000 credits)", "price": 12500},
      {"label": "Pro Plus (2000 credits)", "price": 21000}
    ],
    "imageUrl": "/assets/product-icons/heygen-ai.png",
    "imageAltText": "HeyGen AI subscription plan available in Pakistan",
    "sourceProductUrl": "https://heygen.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "HA",
    "guideUrl": "heygen-ai-pakistan/"
  },
  {
    "productId": "ideogram-ai-plus-private",
    "sku": "ATP-IDEOGRAM-AI",
    "name": "Ideogram AI Plus",
    "sourceProductTitle": "Ideogram AI Plus",
    "slug": "ideogram-ai-plus-private",
    "category": "AI Images and Design",
    "planTier": "Plus plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Shared / Private",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI image design tools",
    "keyFeatures": "AI images; text in images; design; creative assets",
    "shortDescription": "AI image design access for creative visual work.",
    "fullDescription": "Ideogram AI Plus is useful for image generation, creative graphics and text-focused AI image workflows with PKR pricing support.",
    "basePricePkr": 1250,
    "sellingPricePkr": 1500,
    "compareAtPricePkr": 5000,
    "discountPercent": 70,
    "plans": [
      {"label": "Shared Access", "price": 1500},
      {"label": "Private Access", "price": 3000}
    ],
    "planNotes": "Shared account means images may be visible to other users on that account.",
    "imageUrl": "/assets/product-icons/ideogram-ai-plus-private.png",
    "imageAltText": "Ideogram AI Plus subscription plan available in Pakistan",
    "sourceProductUrl": "https://ideogram.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "IA",
    "guideUrl": "ideogram-ai-plus-pakistan/"
  },
  {
    "productId": "success-ai-starter-leads",
    "sku": "ATP-SUCCESS-AI",
    "name": "Success.ai Starter Leads",
    "sourceProductTitle": "Success.ai Starter",
    "slug": "success-ai-starter-leads",
    "category": "Marketing and Lead Generation",
    "planTier": "Starter leads",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "2,000 contacts",
    "keyFeatures": "Lead generation; outreach; email leads; sales workflow",
    "shortDescription": "Lead generation subscription for outreach and sales workflows.",
    "fullDescription": "Success.ai Starter Leads is listed for marketers and agencies that need lead generation and outreach workflow support with clear access terms.",
    "basePricePkr": 2000,
    "sellingPricePkr": 2400,
    "compareAtPricePkr": 3000,
    "discountPercent": 20,
    "imageUrl": "/assets/product-icons/success-ai-starter-leads.png",
    "imageAltText": "Success.ai Starter Leads subscription plan available in Pakistan",
    "sourceProductUrl": "https://success.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "SS",
    "guideUrl": "success-ai-starter-pakistan/"
  },
  {
    "productId": "vidiq",
    "sku": "ATP-VIDIQ",
    "name": "vidIQ",
    "sourceProductTitle": "vidIQ",
    "slug": "vidiq",
    "category": "Marketing and Lead Generation",
    "planTier": "YouTube growth plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "YouTube SEO tools",
    "keyFeatures": "YouTube SEO; keyword ideas; channel growth; content planning",
    "shortDescription": "YouTube growth and SEO tool for creators in Pakistan.",
    "fullDescription": "vidIQ helps YouTube creators research video ideas, improve titles and plan channel growth. Confirm current access details before ordering.",
    "basePricePkr": 1799,
    "sellingPricePkr": 2159,
    "compareAtPricePkr": 2600,
    "discountPercent": 17,
    "imageUrl": "/assets/product-icons/vidiq.png",
    "imageAltText": "vidIQ subscription plan available in Pakistan",
    "sourceProductUrl": "https://vidiq.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "V",
    "guideUrl": "vidiq-pakistan/"
  },
  {
    "productId": "playht",
    "sku": "ATP-PLAYHT",
    "name": "PlayHT",
    "sourceProductTitle": "PlayHT",
    "slug": "playht",
    "category": "AI Voice",
    "planTier": "Voice generation plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI voice generation",
    "keyFeatures": "AI voice; text to speech; narration; dubbing",
    "shortDescription": "AI voice generation tool for narration and audio content.",
    "fullDescription": "PlayHT is useful for creators and businesses that need text-to-speech, narration and AI voice workflows. Confirm usage limits and access before payment.",
    "basePricePkr": 3300,
    "sellingPricePkr": 3960,
    "compareAtPricePkr": 4800,
    "discountPercent": 18,
    "imageUrl": "/assets/product-icons/playht.png",
    "imageAltText": "PlayHT subscription plan available in Pakistan",
    "sourceProductUrl": "https://play.ht",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "P",
    "guideUrl": "playht-pakistan/"
  },
  {
    "productId": "supergrok",
    "sku": "ATP-SUPERGROK",
    "name": "SuperGrok",
    "sourceProductTitle": "SuperGrok",
    "slug": "supergrok",
    "category": "AI Assistants",
    "planTier": "SuperGrok plan",
    "subscriptionDuration": "1–3 months",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Advanced Grok access",
    "keyFeatures": "AI assistant; research; social workflows; current topics",
    "shortDescription": "Grok assistant access for current-topic and social workflows.",
    "fullDescription": "SuperGrok is listed for buyers comparing advanced AI assistants for research, current-topic workflows and productivity. Confirm platform requirements before payment.",
    "basePricePkr": 2083,
    "sellingPricePkr": 2500,
    "compareAtPricePkr": 3500,
    "discountPercent": 29,
    "plans": [
      {"label": "1 Month", "price": 2500},
      {"label": "3 Months", "price": 4500}
    ],
    "imageUrl": "/assets/product-icons/supergrok.png",
    "imageAltText": "SuperGrok subscription plan available in Pakistan",
    "sourceProductUrl": "https://x.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "S",
    "guideUrl": "supergrok-pakistan/"
  },
  {
    "productId": "wordai",
    "sku": "ATP-WORDAI",
    "name": "WordAI",
    "sourceProductTitle": "WordAI",
    "slug": "wordai",
    "category": "Writing and SEO",
    "planTier": "Writing plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Article rewriting tools",
    "keyFeatures": "Rewriting; article spinning; SEO writing; content refresh",
    "shortDescription": "AI rewriting tool for article and SEO content workflows.",
    "fullDescription": "WordAI is useful for rewriting and content-refresh workflows. Buyers should confirm access details, limits and use case suitability before ordering.",
    "basePricePkr": 500,
    "sellingPricePkr": 600,
    "compareAtPricePkr": 900,
    "discountPercent": 33,
    "imageUrl": "/assets/product-icons/wordai.png",
    "imageAltText": "WordAI subscription plan available in Pakistan",
    "sourceProductUrl": "https://wordai.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "W",
    "guideUrl": "wordai-pakistan/"
  },
  {
    "productId": "jasper-ai",
    "sku": "ATP-JASPER-AI",
    "name": "Jasper AI",
    "sourceProductTitle": "Jasper AI",
    "slug": "jasper-ai",
    "category": "Writing and SEO",
    "planTier": "AI copywriting plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI copywriting tools",
    "keyFeatures": "Copywriting; marketing content; brand voice; campaigns",
    "shortDescription": "AI copywriting tool for marketing and content workflows.",
    "fullDescription": "Jasper AI helps marketers, writers and agencies draft campaign copy, brand content and marketing ideas. Confirm plan limits and access before payment.",
    "basePricePkr": 500,
    "sellingPricePkr": 600,
    "compareAtPricePkr": 900,
    "discountPercent": 33,
    "imageUrl": "/assets/product-icons/jasper-ai.png",
    "imageAltText": "Jasper AI subscription plan available in Pakistan",
    "sourceProductUrl": "https://jasper.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "JA",
    "guideUrl": "jasper-ai-pakistan/"
  },
  {
    "productId": "google-ai-ultra-plan",
    "sku": "ATP-GOOGLE-AI-ULTRA",
    "name": "Google AI Ultra Plan",
    "sourceProductTitle": "Google AI Ultra",
    "slug": "google-ai-ultra-plan",
    "category": "AI Assistants",
    "planTier": "Ultra plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Google AI Ultra access",
    "keyFeatures": "Google AI; advanced models; productivity; research",
    "shortDescription": "Google AI Ultra access for advanced Google AI workflows.",
    "fullDescription": "Google AI Ultra Plan is listed for buyers who want advanced Google AI access. Confirm current availability, access method and limits before ordering.",
    "basePricePkr": 1470,
    "sellingPricePkr": 1764,
    "compareAtPricePkr": 2400,
    "discountPercent": 27,
    "imageUrl": "/assets/product-icons/google-ai-ultra-plan.png",
    "imageAltText": "Google AI Ultra Plan subscription available in Pakistan",
    "sourceProductUrl": "https://one.google.com/about/google-ai-plans",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "GA",
    "guideUrl": "google-ai-ultra-pakistan/"
  },
  {
    "productId": "hailuo-ai",
    "sku": "ATP-HAILUO-AI",
    "name": "Hailuo AI",
    "sourceProductTitle": "Hailuo AI",
    "slug": "hailuo-ai",
    "category": "AI Video",
    "planTier": "AI video plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI video generation",
    "keyFeatures": "AI video; prompts; creative clips; video generation",
    "shortDescription": "AI video generation tool for creator experiments and clips.",
    "fullDescription": "Hailuo AI is useful for AI video generation experiments, prompt-based creative clips and creator workflows. Confirm credits, limits and access before payment.",
    "basePricePkr": 1700,
    "sellingPricePkr": 2040,
    "compareAtPricePkr": 2800,
    "discountPercent": 27,
    "imageUrl": "/assets/product-icons/hailuo-ai.png",
    "imageAltText": "Hailuo AI subscription plan available in Pakistan",
    "sourceProductUrl": "https://hailuoai.video",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "HA",
    "guideUrl": "hailuo-ai-pakistan/"
  },
  {
    "productId": "netflix",
    "sku": "ATP-NETFLIX-1SCREEN",
    "name": "Netflix",
    "sourceProductTitle": "Netflix 1 Screen",
    "slug": "netflix",
    "category": "Entertainment",
    "planTier": "1 Screen plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 screen",
    "keyFeatures": "Streaming; movies; series; entertainment",
    "shortDescription": "Netflix 1 screen monthly access for entertainment.",
    "fullDescription": "Netflix 1 screen is listed for buyers in Pakistan who want monthly entertainment access with clear price, duration and WhatsApp order support.",
    "basePricePkr": 417,
    "sellingPricePkr": 500,
    "compareAtPricePkr": 700,
    "discountPercent": 29,
    "imageUrl": "/assets/product-icons/netflix.png",
    "imageAltText": "Netflix 1 screen subscription available in Pakistan",
    "sourceProductUrl": "https://www.netflix.com/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "N",
    "guideUrl": "netflix-pakistan/"
  },
  {
    "productId": "capcut-pro",
    "sku": "ATP-CAPCUT-PRO",
    "name": "CapCut Pro",
    "sourceProductTitle": "CapCut Pro",
    "slug": "capcut-pro",
    "category": "AI Video",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Full editing suite",
    "keyFeatures": "Video editing; templates; effects; AI captions",
    "shortDescription": "Professional video editing app with AI-powered tools and templates.",
    "fullDescription": "CapCut Pro gives access to premium video editing features including advanced effects, AI captions, pro templates and high-quality exports for content creators.",
    "basePricePkr": 750,
    "sellingPricePkr": 900,
    "compareAtPricePkr": 1500,
    "discountPercent": 40,
    "imageUrl": "/assets/product-icons/capcut.ico",
    "imageAltText": "CapCut Pro subscription plan available in Pakistan",
    "sourceProductUrl": "https://www.capcut.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "CC",
    "guideUrl": "capcut-pro-pakistan/"
  },
  {
    "productId": "veo-3-extension",
    "sku": "ATP-VEO3-EXT",
    "name": "Veo 3 Extension",
    "sourceProductTitle": "Veo 3 Extension",
    "slug": "veo-3-extension",
    "category": "AI Video",
    "planTier": "Extension plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI video generation",
    "keyFeatures": "Veo 3 access; AI video; text to video; Google AI",
    "shortDescription": "Access Google Veo 3 AI video generation through browser extension.",
    "fullDescription": "Veo 3 Extension provides access to Google's Veo 3 AI video generation model. Create high-quality AI videos from text prompts with advanced generation features.",
    "basePricePkr": 2500,
    "sellingPricePkr": 3000,
    "compareAtPricePkr": 4500,
    "discountPercent": 33,
    "imageUrl": "/assets/product-icons/gemini-pro.png",
    "imageAltText": "Veo 3 Extension subscription plan available in Pakistan",
    "sourceProductUrl": "https://deepmind.google/technologies/veo/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "V3",
    "guideUrl": "veo-3-pakistan/"
  },
  {
    "productId": "claude-20x-max",
    "sku": "ATP-CLAUDE-20X-MAX",
    "name": "Claude 20X Max Plan",
    "sourceProductTitle": "Claude 20X Max Plan",
    "slug": "claude-20x-max",
    "category": "AI Assistants",
    "planTier": "20X Max plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "20x usage limit",
    "keyFeatures": "Claude AI; 20x usage; coding; research; long writing",
    "shortDescription": "Claude Max plan with 20x usage for heavy AI workloads.",
    "fullDescription": "Claude 20X Max Plan is the highest-tier Claude subscription offering 20x the standard usage limits. Ideal for developers, researchers and power users who need maximum AI capacity.",
    "basePricePkr": 37500,
    "sellingPricePkr": 45000,
    "compareAtPricePkr": 57000,
    "discountPercent": 30,
    "imageUrl": "/assets/product-icons/claude-ai.png",
    "imageAltText": "Claude 20X Max Plan subscription available in Pakistan",
    "sourceProductUrl": "https://claude.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "CM",
    "guideUrl": ""
  },
  {
    "productId": "veo-3-ultra",
    "sku": "ATP-VEO3-ULTRA",
    "name": "Veo 3 Ultra – Official Paid Invite",
    "sourceProductTitle": "Veo 3 Ultra",
    "slug": "veo-3-ultra",
    "category": "AI Video",
    "planTier": "Ultra invite",
    "subscriptionDuration": "Credit-based",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "200–1000 credits",
    "keyFeatures": "Veo 3 official; paid invite; AI video; premium access",
    "shortDescription": "Official Veo 3 paid invite access with credit-based pricing tiers.",
    "fullDescription": "Veo 3 Ultra gives official paid invite access to Google's Veo 3 AI video generation. Choose from credit tiers to match your production needs.",
    "basePricePkr": 7083,
    "sellingPricePkr": 8500,
    "compareAtPricePkr": 12000,
    "discountPercent": 29,
    "plans": [
      {"label": "200 Credits", "price": 8500},
      {"label": "500 Credits", "price": 13500},
      {"label": "1000 Credits", "price": 25000}
    ],
    "imageUrl": "/assets/product-icons/gemini-pro.png",
    "imageAltText": "Veo 3 Ultra official paid invite available in Pakistan",
    "sourceProductUrl": "https://deepmind.google/technologies/veo/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "VU",
    "guideUrl": ""
  },
  {
    "productId": "dzine-master",
    "sku": "ATP-DZINE-MASTER",
    "name": "Dzine Master",
    "sourceProductTitle": "Dzine Master",
    "slug": "dzine-master",
    "category": "AI Images and Design",
    "planTier": "Master plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Full design suite",
    "keyFeatures": "AI design; image editing; creative tools; templates",
    "shortDescription": "AI-powered design suite for professional image creation and editing.",
    "fullDescription": "Dzine Master provides a complete AI design toolkit for creating professional graphics, editing images and accessing premium design templates and tools.",
    "basePricePkr": 4167,
    "sellingPricePkr": 5000,
    "compareAtPricePkr": 7000,
    "discountPercent": 29,
    "imageUrl": "/assets/product-icons/dzine.ico",
    "imageAltText": "Dzine Master subscription plan available in Pakistan",
    "sourceProductUrl": "https://www.dzine.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "DZ",
    "guideUrl": ""
  },
  {
    "productId": "storyblocks-unlimited",
    "sku": "ATP-STORYBLOCKS",
    "name": "Storyblocks Unlimited",
    "sourceProductTitle": "Storyblocks Unlimited",
    "slug": "storyblocks-unlimited",
    "category": "AI Video",
    "planTier": "Unlimited plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Unlimited downloads",
    "keyFeatures": "Stock video; stock audio; templates; unlimited downloads",
    "shortDescription": "Unlimited stock video, audio and template downloads for creators.",
    "fullDescription": "Storyblocks Unlimited gives access to a massive library of royalty-free stock video, audio, images and templates with unlimited downloads for content creation.",
    "basePricePkr": 3333,
    "sellingPricePkr": 4000,
    "compareAtPricePkr": 6000,
    "discountPercent": 33,
    "imageUrl": "/assets/product-icons/storyblocks.svg",
    "imageAltText": "Storyblocks Unlimited subscription available in Pakistan",
    "sourceProductUrl": "https://www.storyblocks.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "SB",
    "guideUrl": ""
  },
  {
    "productId": "prime-video",
    "sku": "ATP-PRIME-VIDEO",
    "name": "Prime Video",
    "sourceProductTitle": "Prime Video",
    "slug": "prime-video",
    "category": "Entertainment",
    "planTier": "Standard plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 screen",
    "keyFeatures": "Streaming; movies; series; Amazon originals",
    "shortDescription": "Amazon Prime Video streaming access for movies and series.",
    "fullDescription": "Prime Video provides access to Amazon's streaming library including original series, movies and exclusive content with monthly subscription in Pakistan.",
    "basePricePkr": 333,
    "sellingPricePkr": 400,
    "compareAtPricePkr": 700,
    "discountPercent": 43,
    "imageUrl": "/assets/product-icons/prime-video.ico",
    "imageAltText": "Prime Video subscription available in Pakistan",
    "sourceProductUrl": "https://www.primevideo.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "PV",
    "guideUrl": ""
  },
  {
    "productId": "coursera-premium",
    "sku": "ATP-COURSERA",
    "name": "Coursera Premium",
    "sourceProductTitle": "Coursera Premium",
    "slug": "coursera-premium",
    "category": "Writing and SEO",
    "planTier": "Premium plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Full course access",
    "keyFeatures": "Online courses; certifications; learning; skill building",
    "shortDescription": "Premium access to Coursera courses and certifications.",
    "fullDescription": "Coursera Premium provides access to thousands of online courses, professional certifications and learning paths from top universities and companies.",
    "basePricePkr": 833,
    "sellingPricePkr": 1000,
    "compareAtPricePkr": 1800,
    "discountPercent": 44,
    "imageUrl": "/assets/product-icons/coursera.ico",
    "imageAltText": "Coursera Premium subscription available in Pakistan",
    "sourceProductUrl": "https://www.coursera.org",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "C",
    "guideUrl": ""
  },
  {
    "productId": "helium-10-platinum",
    "sku": "ATP-HELIUM10-PLAT",
    "name": "Helium 10 Platinum",
    "sourceProductTitle": "Helium 10 Platinum",
    "slug": "helium-10-platinum",
    "category": "Marketing and Lead Generation",
    "planTier": "Platinum plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Amazon seller tools",
    "keyFeatures": "Amazon FBA; product research; keyword tracking; listing optimization",
    "shortDescription": "Amazon seller toolkit for product research and listing optimization.",
    "fullDescription": "Helium 10 Platinum provides Amazon sellers with product research, keyword tracking, listing optimization and competitive analysis tools for FBA businesses.",
    "basePricePkr": 2083,
    "sellingPricePkr": 2500,
    "compareAtPricePkr": 4000,
    "discountPercent": 38,
    "imageUrl": "/assets/product-icons/helium-10.ico",
    "imageAltText": "Helium 10 Platinum subscription available in Pakistan",
    "sourceProductUrl": "https://www.helium10.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "H10",
    "guideUrl": ""
  },
  {
    "productId": "helium-10-diamond",
    "sku": "ATP-HELIUM10-DIAMOND",
    "name": "Helium 10 Diamond",
    "sourceProductTitle": "Helium 10 Diamond",
    "slug": "helium-10-diamond",
    "category": "Marketing and Lead Generation",
    "planTier": "Diamond plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Advanced Amazon tools",
    "keyFeatures": "Amazon FBA; advanced analytics; multi-user; inventory management",
    "shortDescription": "Advanced Amazon seller suite with expanded tools and analytics.",
    "fullDescription": "Helium 10 Diamond is the advanced tier for serious Amazon sellers, offering expanded analytics, multi-user access, inventory management and full-suite seller tools.",
    "basePricePkr": 3750,
    "sellingPricePkr": 4500,
    "compareAtPricePkr": 7000,
    "discountPercent": 36,
    "imageUrl": "/assets/product-icons/helium-10.ico",
    "imageAltText": "Helium 10 Diamond subscription available in Pakistan",
    "sourceProductUrl": "https://www.helium10.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "H10",
    "guideUrl": ""
  },
  {
    "productId": "semrush-pro",
    "sku": "ATP-SEMRUSH-PRO",
    "name": "SEMrush Pro",
    "sourceProductTitle": "SEMrush Pro",
    "slug": "semrush-pro",
    "category": "Marketing and Lead Generation",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "SEO and marketing tools",
    "keyFeatures": "SEO audit; keyword research; competitor analysis; backlink tracking",
    "shortDescription": "All-in-one SEO and marketing toolkit for keyword research and audits.",
    "fullDescription": "SEMrush Pro provides comprehensive SEO and digital marketing tools including keyword research, site audits, competitor analysis, backlink tracking and rank monitoring.",
    "basePricePkr": 1250,
    "sellingPricePkr": 1500,
    "compareAtPricePkr": 2500,
    "discountPercent": 40,
    "imageUrl": "/assets/product-icons/semrush.ico",
    "imageAltText": "SEMrush Pro subscription available in Pakistan",
    "sourceProductUrl": "https://www.semrush.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "SE",
    "guideUrl": ""
  }
];
