window.AI_TOOLS_PRODUCTS = [
  {
    "productId": "gemini-pro",
    "sku": "ATP-GEMINI-PRO",
    "name": "Gemini Pro — 18 Months",
    "sourceProductTitle": "Gemini Advanced",
    "slug": "gemini-pro",
    "category": "AI Assistants",
    "planTier": "Pro plan",
    "subscriptionDuration": "18 months",
    "durationMonths": 18,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Google AI access",
    "keyFeatures": "Google AI; writing; productivity; research",
    "shortDescription": "Google AI assistant access with an 18-month plan.",
    "fullDescription": "Gemini Pro is listed with PKR pricing, private access and WhatsApp order support in Pakistan for buyers seeking an 18-month plan. Confirm current availability and delivery details on WhatsApp before ordering.",
    "basePricePkr": 800,
    "sellingPricePkr": 800,
    "compareAtPricePkr": 1500,
    "discountPercent": 47,
    "imageUrl": "/assets/product-icons/gemini-pro.png",
    "imageAltText": "Gemini Pro — 18 Months brand icon",
    "sourceProductUrl": "https://gemini.google.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "GP",
    "guideUrl": "gemini-pro-pakistan/"
  },
  {
    "productId": "chatgpt-plus",
    "sku": "ATP-CHATGPT-PLUS",
    "name": "ChatGPT Plus",
    "sourceProductTitle": "ChatGPT Plus",
    "slug": "chatgpt-plus",
    "category": "AI Assistants",
    "planTier": "Plus plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Advanced AI assistant",
    "keyFeatures": "Writing; research; coding help; brainstorming",
    "shortDescription": "All-round AI assistant for writing, study, coding and business work.",
    "fullDescription": "ChatGPT Plus is useful for students, freelancers and teams that need one flexible assistant for daily writing, research, coding support and planning.",
    "basePricePkr": 2200,
    "sellingPricePkr": 2200,
    "compareAtPricePkr": 3000,
    "discountPercent": 27,
    "imageUrl": "/assets/product-icons/chatgpt-plus.png",
    "imageAltText": "ChatGPT Plus brand icon",
    "sourceProductUrl": "https://chatgpt.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "CP",
    "guideUrl": "chatgpt-plus-pakistan/"
  },
  {
    "productId": "veo-3-extension",
    "sku": "ATP-VEO3-EXT",
    "name": "Veo 3 Extension — 30 Days",
    "sourceProductTitle": "Veo 3 Extension",
    "slug": "veo-3-extension",
    "category": "AI Video",
    "planTier": "Extension plan",
    "subscriptionDuration": "30 days",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Unlimited video generation",
    "keyFeatures": "AI video; 30 days; unlimited video generation",
    "shortDescription": "Veo 3 Extension with a 30-day plan and listed unlimited video generation.",
    "fullDescription": "Veo 3 Extension is listed with PKR pricing and WhatsApp order support in Pakistan. Confirm availability, delivery method and current usage terms before ordering.",
    "basePricePkr": 2100,
    "sellingPricePkr": 2100,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/gemini-pro.png",
    "imageAltText": "Gemini Pro logo",
    "sourceProductUrl": "https://deepmind.google/technologies/veo/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "V3",
    "guideUrl": "veo-3-extension-pakistan/"
  },
  {
    "productId": "elevenlabs-creator-private",
    "sku": "ATP-ELEVENLABS-CREATOR",
    "name": "ElevenLabs Creator — 130K Credits",
    "sourceProductTitle": "ElevenLabs Creator",
    "slug": "elevenlabs-creator-private",
    "category": "AI Voice",
    "planTier": "Creator plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "130K credits",
    "keyFeatures": "AI voice; 130K credits; 1 month",
    "shortDescription": "ElevenLabs Creator plan with 130K credits and PKR pricing.",
    "fullDescription": "ElevenLabs Creator is listed as a 130K-credit plan for AI voice workflows. Confirm the current credit allocation, availability and delivery details before ordering.",
    "basePricePkr": 3300,
    "sellingPricePkr": 3300,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/elevenlabs-creator-private.png",
    "imageAltText": "ElevenLabs Creator — 130K Credits brand icon",
    "sourceProductUrl": "https://elevenlabs.io",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "EC",
    "guideUrl": "elevenlabs-creator-pakistan/"
  },
  {
    "productId": "lovable-ai-pro-private",
    "sku": "ATP-LOVABLE-AI-PRO",
    "name": "Lovable Pro — 1 Month",
    "sourceProductTitle": "Lovable Pro",
    "slug": "lovable-ai-pro-private",
    "category": "Development and Coding",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 month access",
    "keyFeatures": "App building; coding; 1 month",
    "shortDescription": "Lovable Pro monthly plan with PKR pricing.",
    "fullDescription": "Lovable Pro is listed for app-building workflows with PKR pricing and WhatsApp order support. Confirm access, availability and delivery details before ordering.",
    "basePricePkr": 1600,
    "sellingPricePkr": 1600,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/lovable-ai-pro-private.jpg",
    "imageAltText": "Lovable Pro — 1 Month brand icon",
    "sourceProductUrl": "https://lovable.dev",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "LP",
    "guideUrl": "lovable-ai-pro-pakistan/"
  },
  {
    "productId": "claude-ai",
    "sku": "ATP-CLAUDE-AI",
    "name": "Claude Pro",
    "sourceProductTitle": "Claude Pro",
    "slug": "claude-ai",
    "category": "Development and Coding",
    "planTier": "AI assistant plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Writing and coding assistant",
    "keyFeatures": "Long writing; research; code review; summaries",
    "shortDescription": "Careful AI assistant for long writing, research and coding support.",
    "fullDescription": "Claude AI is suitable for students, writers and developers who need structured output, careful rewriting, long-document help and code explanation.",
    "basePricePkr": 5500,
    "sellingPricePkr": 5500,
    "compareAtPricePkr": 7000,
    "discountPercent": 21,
    "imageUrl": "/assets/product-icons/claude-ai.png",
    "imageAltText": "Claude Pro brand icon",
    "sourceProductUrl": "https://claude.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "CP",
    "guideUrl": "claude-pro-pakistan/"
  },
  {
    "productId": "runway-ml-unlimited-generations",
    "sku": "ATP-RUNWAY-ML",
    "name": "Runway ML Pro",
    "sourceProductTitle": "Runway Pro",
    "slug": "runway-ml-unlimited-generations",
    "category": "AI Video",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "2250 credits",
    "keyFeatures": "AI video; generation; editing; creative workflow",
    "shortDescription": "AI video generation access for creator and agency workflows.",
    "fullDescription": "Runway ML Pro includes 2,250 credits per month, full private access and warranty on delivery. Official Runway Pro pricing is USD 28/month (~PKR 7,779) — AI Tools Pak lists it at PKR 5,500.",
    "basePricePkr": 5500,
    "sellingPricePkr": 5500,
    "compareAtPricePkr": 7779,
    "discountPercent": 29,
    "imageUrl": "/assets/product-icons/runway-ml-unlimited-generations.png",
    "imageAltText": "Runway ML Pro brand icon",
    "sourceProductUrl": "https://runwayml.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "RM",
    "guideUrl": "runway-ml-pakistan/"
  },
  {
    "productId": "leonardo-ai",
    "sku": "ATP-LEONARDO-AI",
    "name": "Leonardo AI",
    "sourceProductTitle": "Leonardo AI",
    "slug": "leonardo-ai",
    "category": "AI Images and Design",
    "planTier": "Design plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI image generation access",
    "keyFeatures": "AI images; design; creative assets; prompts",
    "shortDescription": "AI image and design subscription for creative visual workflows.",
    "fullDescription": "Leonardo AI access for AI image and design workflows, full private access with warranty. Official Apprentice pricing is USD 10/month (~PKR 2,778) — AI Tools Pak lists it at PKR 2,200.",
    "basePricePkr": 2200,
    "sellingPricePkr": 2200,
    "compareAtPricePkr": 2778,
    "discountPercent": 21,
    "imageUrl": "/assets/product-icons/leonardo-ai.png",
    "imageAltText": "Leonardo AI brand icon",
    "sourceProductUrl": "https://leonardo.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "LA",
    "guideUrl": "leonardo-ai-pakistan/"
  },
  {
    "productId": "grammarly-pro",
    "sku": "ATP-GRAMMARLY-PRO",
    "name": "Grammarly Premium",
    "sourceProductTitle": "Grammarly Premium",
    "slug": "grammarly-pro",
    "category": "Writing and SEO",
    "planTier": "Premium plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Grammar and writing tools",
    "keyFeatures": "Grammar; rewriting; proofreading; writing clarity",
    "shortDescription": "Writing assistant for grammar, rewriting and clarity checks.",
    "fullDescription": "Grammarly Premium is useful for students, writers and freelancers who want grammar checking, proofreading, rewriting suggestions and clearer English output.",
    "basePricePkr": 1000,
    "sellingPricePkr": 1000,
    "compareAtPricePkr": 1200,
    "discountPercent": 17,
    "imageUrl": "/assets/product-icons/grammarly-pro.png",
    "imageAltText": "Grammarly Premium brand icon",
    "sourceProductUrl": "https://grammarly.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "GP",
    "guideUrl": "grammarly-premium-pakistan/"
  },
  {
    "productId": "quillbot",
    "sku": "ATP-QUILLBOT",
    "name": "QuillBot",
    "sourceProductTitle": "QuillBot",
    "slug": "quillbot",
    "category": "Writing and SEO",
    "planTier": "Writing plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Paraphrasing and writing tools",
    "keyFeatures": "Paraphrasing; summarizing; grammar; writing workflow",
    "shortDescription": "Paraphrasing and writing support for students and freelancers.",
    "fullDescription": "QuillBot helps with paraphrasing, rewriting, summaries and grammar workflows for buyers who need affordable writing support.",
    "basePricePkr": 479,
    "sellingPricePkr": 479,
    "compareAtPricePkr": 700,
    "discountPercent": 32,
    "imageUrl": "/assets/product-icons/quillbot.png",
    "imageAltText": "QuillBot brand icon",
    "sourceProductUrl": "https://quillbot.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "Q",
    "guideUrl": "quillbot-premium-pakistan/"
  },
  {
    "productId": "heygen-ai",
    "sku": "ATP-HEYGEN-AI",
    "name": "HeyGen AI",
    "sourceProductTitle": "HeyGen AI",
    "slug": "heygen-ai",
    "category": "AI Video",
    "planTier": "Creator / Pro / Pro Plus",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "600–2000 credits",
    "keyFeatures": "AI avatars; text to video; presentations; creator video",
    "shortDescription": "AI avatar and text-to-video tool for creator workflows.",
    "fullDescription": "HeyGen AI is listed for buyers who need avatar videos, text-to-video workflows and creator-friendly video production support.",
    "basePricePkr": 7400,
    "sellingPricePkr": 7400,
    "compareAtPricePkr": 10000,
    "discountPercent": 26,
    "imageUrl": "/assets/product-icons/heygen-ai.png",
    "imageAltText": "HeyGen AI brand icon",
    "sourceProductUrl": "https://heygen.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "HA",
    "guideUrl": "heygen-ai-pakistan/"
  },
  {
    "productId": "supergrok",
    "sku": "ATP-SUPERGROK",
    "name": "SuperGrok",
    "sourceProductTitle": "SuperGrok",
    "slug": "supergrok",
    "category": "AI Assistants",
    "planTier": "SuperGrok plan",
    "subscriptionDuration": "1–3 months",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Advanced Grok access",
    "keyFeatures": "AI assistant; research; social workflows; current topics",
    "shortDescription": "Grok assistant access for current-topic and social workflows.",
    "fullDescription": "SuperGrok is listed for buyers comparing advanced AI assistants for research, current-topic workflows and productivity. Confirm platform requirements before payment.",
    "basePricePkr": 2500,
    "sellingPricePkr": 2500,
    "compareAtPricePkr": 3500,
    "discountPercent": 29,
    "imageUrl": "/assets/product-icons/supergrok.png",
    "imageAltText": "SuperGrok brand icon",
    "sourceProductUrl": "https://x.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "S",
    "guideUrl": "supergrok-pakistan/"
  },
  {
    "productId": "google-ai-ultra-plan",
    "sku": "ATP-GOOGLE-AI-ULTRA",
    "name": "Google AI Ultra Plan",
    "sourceProductTitle": "Google AI Ultra",
    "slug": "google-ai-ultra-plan",
    "category": "AI Assistants",
    "planTier": "Ultra plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Google AI Ultra access",
    "keyFeatures": "Google AI; advanced models; productivity; research; premium tier above Gemini Pro",
    "shortDescription": "Google AI Ultra access for advanced Google AI workflows.",
    "fullDescription": "Google AI Ultra Plan delivers the higher Google AI tier for advanced workflows, above the standard Gemini Pro plan, with PKR pricing and WhatsApp order support in Pakistan. Confirm current availability, access method and limits before ordering. If the standard Gemini Pro tier meets your needs, the separate Gemini Pro listing is the more affordable option.",
    "basePricePkr": 1764,
    "sellingPricePkr": 1764,
    "compareAtPricePkr": 2400,
    "discountPercent": 27,
    "imageUrl": "/assets/product-icons/google-ai-ultra-plan.png",
    "imageAltText": "Google AI Ultra Plan brand icon",
    "sourceProductUrl": "https://one.google.com/about/google-ai-plans",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "GA",
    "guideUrl": "google-ai-ultra-pakistan/"
  },
  {
    "productId": "netflix",
    "sku": "ATP-NETFLIX-1SCREEN",
    "name": "Netflix Premium 4K — 1 Month",
    "sourceProductTitle": "Netflix Premium 4K",
    "slug": "netflix",
    "category": "Entertainment",
    "planTier": "Premium 4K plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 month access",
    "keyFeatures": "Streaming; movies; series; 4K plan details confirmed before ordering",
    "shortDescription": "Netflix Premium 4K monthly access for entertainment.",
    "fullDescription": "Netflix Premium 4K is listed with a clear PKR price, one-month duration and WhatsApp order support. Confirm the current plan details, availability and delivery method before ordering. Netflix is an entertainment service, not an AI tool.",
    "basePricePkr": 400,
    "sellingPricePkr": 400,
    "compareAtPricePkr": 700,
    "discountPercent": 43,
    "imageUrl": "/assets/product-icons/netflix.png",
    "imageAltText": "Netflix Premium 4K — 1 Month brand icon",
    "sourceProductUrl": "https://www.netflix.com/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "NP",
    "guideUrl": "netflix-pakistan/"
  },
  {
    "productId": "capcut-pro",
    "sku": "ATP-CAPCUT-PRO",
    "name": "CapCut Pro — 1 Month",
    "sourceProductTitle": "CapCut Pro",
    "slug": "capcut-pro",
    "category": "AI Video",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 month access",
    "keyFeatures": "Video editing; templates; effects; AI captions",
    "shortDescription": "Professional video editing with AI-powered tools and templates for one month.",
    "fullDescription": "CapCut Pro is listed for one month with PKR pricing and WhatsApp order support. Confirm current plan access, availability and delivery details before ordering.",
    "basePricePkr": 900,
    "sellingPricePkr": 900,
    "compareAtPricePkr": 1500,
    "discountPercent": 40,
    "imageUrl": "/assets/product-icons/capcut-pro.png",
    "imageAltText": "CapCut Pro — 1 Month brand icon",
    "sourceProductUrl": "https://www.capcut.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "CP",
    "guideUrl": "capcut-pro-pakistan/"
  },
  {
    "productId": "claude-20x-max",
    "sku": "ATP-CLAUDE-20X-MAX",
    "name": "Claude 20X Max Plan",
    "sourceProductTitle": "Claude 20X Max Plan",
    "slug": "claude-20x-max",
    "category": "AI Assistants",
    "planTier": "20X Max plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "20x usage limit",
    "keyFeatures": "Claude AI; 20x usage; coding; research; long writing",
    "shortDescription": "Claude Max plan with 20x usage for heavy AI workloads.",
    "fullDescription": "Claude 20X Max Plan is the highest-tier Claude subscription offering 20x the standard usage limits. Ideal for developers, researchers and power users who need maximum AI capacity.",
    "basePricePkr": 45000,
    "sellingPricePkr": 45000,
    "compareAtPricePkr": 57000,
    "discountPercent": 21,
    "imageUrl": "/assets/product-icons/claude-20x-max.png",
    "imageAltText": "Claude 20X Max Plan brand icon",
    "sourceProductUrl": "https://claude.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "C2",
    "guideUrl": "claude-20x-max-pakistan/"
  },
  {
    "productId": "veo-3-ultra",
    "sku": "ATP-VEO3-ULTRA",
    "name": "Veo 3 Ultra – Official Paid Invite",
    "sourceProductTitle": "Veo 3 Ultra",
    "slug": "veo-3-ultra",
    "category": "AI Video",
    "planTier": "Ultra invite",
    "subscriptionDuration": "Credit-based",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "200–1000 credits",
    "keyFeatures": "Veo 3 official; paid invite; AI video; premium access",
    "shortDescription": "Official Veo 3 paid invite access with credit-based pricing tiers.",
    "fullDescription": "Veo 3 Ultra gives official paid invite access to Google's Veo 3 AI video generation. Choose from credit tiers to match your production needs.",
    "basePricePkr": 8500,
    "sellingPricePkr": 8500,
    "compareAtPricePkr": 12000,
    "discountPercent": 29,
    "imageUrl": "/assets/product-icons/gemini-pro.png",
    "imageAltText": "Gemini Pro logo",
    "sourceProductUrl": "https://deepmind.google/technologies/veo/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "V3",
    "guideUrl": "veo-3-ultra-pakistan/"
  },
  {
    "productId": "prime-video",
    "sku": "ATP-PRIME-VIDEO",
    "name": "Prime Video",
    "sourceProductTitle": "Prime Video",
    "slug": "prime-video",
    "category": "Entertainment",
    "planTier": "Standard plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 screen",
    "keyFeatures": "Streaming; movies; series; Amazon originals; not an AI tool",
    "shortDescription": "Amazon Prime Video streaming access for movies and series.",
    "fullDescription": "Prime Video provides access to Amazon's streaming library including original series, movies and exclusive content with a monthly subscription in Pakistan. Note: Prime Video is a streaming service, not an AI tool. AI Tools Pak also lists AI subscriptions if you need AI software for work or study.",
    "basePricePkr": 400,
    "sellingPricePkr": 400,
    "compareAtPricePkr": 700,
    "discountPercent": 43,
    "imageUrl": "/assets/product-icons/prime-video.png",
    "imageAltText": "Prime Video brand icon",
    "sourceProductUrl": "https://www.primevideo.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "PV",
    "guideUrl": "prime-video-pakistan/"
  },
  {
    "productId": "helium-10-platinum",
    "sku": "ATP-HELIUM10-PLAT",
    "name": "Helium 10 Platinum",
    "sourceProductTitle": "Helium 10 Platinum",
    "slug": "helium-10-platinum",
    "category": "Marketing and Lead Generation",
    "planTier": "Platinum plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Amazon seller tools",
    "keyFeatures": "Amazon FBA; product research; keyword tracking; listing optimization",
    "shortDescription": "Amazon seller toolkit for product research and listing optimization.",
    "fullDescription": "Helium 10 Platinum provides Amazon sellers with product research, keyword tracking, listing optimization and competitive analysis tools for FBA businesses.",
    "basePricePkr": 2500,
    "sellingPricePkr": 2500,
    "compareAtPricePkr": 4000,
    "discountPercent": 38,
    "imageUrl": "/assets/product-icons/helium-10-platinum.png",
    "imageAltText": "Helium 10 Platinum brand icon",
    "sourceProductUrl": "https://www.helium10.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "H1",
    "guideUrl": "helium-10-platinum-pakistan/"
  },
  {
    "productId": "helium-10-diamond",
    "sku": "ATP-HELIUM10-DIAMOND",
    "name": "Helium 10 Diamond",
    "sourceProductTitle": "Helium 10 Diamond",
    "slug": "helium-10-diamond",
    "category": "Marketing and Lead Generation",
    "planTier": "Diamond plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Advanced Amazon tools",
    "keyFeatures": "Amazon FBA; advanced analytics; multi-user; inventory management",
    "shortDescription": "Advanced Amazon seller suite with expanded tools and analytics.",
    "fullDescription": "Helium 10 Diamond is the advanced tier for serious Amazon sellers, offering expanded analytics, multi-user access, inventory management and full-suite seller tools.",
    "basePricePkr": 4500,
    "sellingPricePkr": 4500,
    "compareAtPricePkr": 7000,
    "discountPercent": 36,
    "imageUrl": "/assets/product-icons/helium-10-diamond.png",
    "imageAltText": "Helium 10 Diamond brand icon",
    "sourceProductUrl": "https://www.helium10.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "H1",
    "guideUrl": "helium-10-diamond-pakistan/"
  },
  {
    "productId": "runway-ml-max",
    "sku": "ATP-RUNWAY-ML-MAX",
    "name": "Runway ML Max",
    "sourceProductTitle": "Runway Max",
    "slug": "runway-ml-max",
    "category": "AI Video",
    "planTier": "Max plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "9500 credits",
    "keyFeatures": "AI video; generation; editing; 9500 credits; rollover",
    "shortDescription": "Runway ML Max AI video generation with 9,500 monthly credits.",
    "fullDescription": "Runway ML Max includes 9,500 credits per month with unused credits rolling over for one month, first access to newest models and highest generation volume. Official Runway Max pricing is USD 76/month (~PKR 21,115) — AI Tools Pak lists it at PKR 14,000 with full private access and warranty.",
    "basePricePkr": 14000,
    "sellingPricePkr": 14000,
    "compareAtPricePkr": 21115,
    "discountPercent": 34,
    "imageUrl": "/assets/product-icons/runway-ml-max.png",
    "imageAltText": "Runway ML Max brand icon",
    "sourceProductUrl": "https://runwayml.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "RM",
    "guideUrl": "runway-ml-max-pakistan/"
  },
  {
    "productId": "canva-pro",
    "sku": "ATP-CANVA-PRO",
    "name": "Canva Pro",
    "sourceProductTitle": "Canva Pro",
    "slug": "canva-pro",
    "category": "AI Images and Design",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 month access",
    "keyFeatures": "Design tools; templates; brand tools; content creation",
    "shortDescription": "Canva Pro monthly plan with PKR pricing and WhatsApp order support.",
    "fullDescription": "Canva Pro is listed for buyers in Pakistan who need a monthly design-tool subscription. Confirm current plan access, availability and delivery details before ordering.",
    "basePricePkr": 900,
    "sellingPricePkr": 900,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/canva-pro.jpg",
    "imageAltText": "Canva Pro brand icon",
    "sourceProductUrl": "https://www.canva.com/pro/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "CP",
    "guideUrl": "canva-pro-pakistan/"
  },
  {
    "productId": "leonardo-ai-essential-8500-credits",
    "sku": "ATP-LEONARDO-ESS-8500",
    "name": "Leonardo AI Essential — 8,500 Credits",
    "sourceProductTitle": "Leonardo AI Essential",
    "slug": "leonardo-ai-essential-8500-credits",
    "category": "AI Images and Design",
    "planTier": "Essential plan",
    "subscriptionDuration": "",
    "durationMonths": null,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "8,500 credits",
    "keyFeatures": "AI images; 8,500 credits; design workflows",
    "shortDescription": "Leonardo AI Essential plan with 8,500 credits and PKR pricing.",
    "fullDescription": "Leonardo AI Essential is listed as a distinct credit-based plan for buyers in Pakistan. Confirm current credit allocation, access method and delivery details before ordering.",
    "basePricePkr": 1900,
    "sellingPricePkr": 1900,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/leonardo-ai-essential-8500-credits.png",
    "imageAltText": "Leonardo AI Essential — 8,500 Credits brand icon",
    "sourceProductUrl": "https://leonardo.ai/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "LA",
    "guideUrl": "leonardo-ai-essential-8500-credits-pakistan/"
  },
  {
    "productId": "nordvpn-3-months",
    "sku": "ATP-NORDVPN-3M",
    "name": "NordVPN — 3 Months",
    "sourceProductTitle": "NordVPN",
    "slug": "nordvpn-3-months",
    "category": "VPN & Privacy",
    "planTier": "3-month plan",
    "subscriptionDuration": "3 months",
    "durationMonths": 3,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "3 months access",
    "keyFeatures": "VPN; privacy; 3 months",
    "shortDescription": "NordVPN plan with a three-month duration and PKR pricing.",
    "fullDescription": "NordVPN is listed for buyers in Pakistan who need a three-month VPN and privacy plan. Confirm availability, account access and delivery details before ordering.",
    "basePricePkr": 1800,
    "sellingPricePkr": 1800,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/nordvpn-3-months.png",
    "imageAltText": "NordVPN — 3 Months brand icon",
    "sourceProductUrl": "https://nordvpn.com/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "N—",
    "guideUrl": "nordvpn-3-months-pakistan/"
  },
  {
    "productId": "surfshark-vpn-2-months",
    "sku": "ATP-SURFSHARK-2M",
    "name": "Surfshark VPN — 2 Months",
    "sourceProductTitle": "Surfshark VPN",
    "slug": "surfshark-vpn-2-months",
    "category": "VPN & Privacy",
    "planTier": "2-month plan",
    "subscriptionDuration": "2 months",
    "durationMonths": 2,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "2 months access",
    "keyFeatures": "VPN; privacy; 2 months",
    "shortDescription": "Surfshark VPN plan with a two-month duration and PKR pricing.",
    "fullDescription": "Surfshark VPN is listed for buyers in Pakistan who need a two-month VPN and privacy plan. Confirm availability, account access and delivery details before ordering.",
    "basePricePkr": 800,
    "sellingPricePkr": 800,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/surfshark-vpn-2-months.png",
    "imageAltText": "Surfshark VPN — 2 Months brand icon",
    "sourceProductUrl": "https://surfshark.com/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "SV",
    "guideUrl": "surfshark-vpn-2-months-pakistan/"
  },
  {
    "productId": "youtube-premium-3-months",
    "sku": "ATP-YOUTUBE-PREM-3M",
    "name": "YouTube Premium — 3 Months",
    "sourceProductTitle": "YouTube Premium",
    "slug": "youtube-premium-3-months",
    "category": "Entertainment",
    "planTier": "3-month plan",
    "subscriptionDuration": "3 months",
    "durationMonths": 3,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "3 months access",
    "keyFeatures": "Video; music; ad-free viewing; 3 months",
    "shortDescription": "YouTube Premium plan with a three-month duration and PKR pricing.",
    "fullDescription": "YouTube Premium is listed for buyers in Pakistan who need a three-month entertainment plan. Confirm availability, account access and delivery details before ordering.",
    "basePricePkr": 1200,
    "sellingPricePkr": 1200,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/youtube-premium-3-months.png",
    "imageAltText": "YouTube Premium — 3 Months brand icon",
    "sourceProductUrl": "https://www.youtube.com/premium",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "YP",
    "guideUrl": "youtube-premium-3-months-pakistan/"
  },
  {
    "productId": "canva-pro-edu-1-year",
    "sku": "ATP-CANVA-EDU-1Y",
    "name": "Canva Pro Edu — 1 Year Invite",
    "sourceProductTitle": "Canva for Education",
    "slug": "canva-pro-edu-1-year",
    "category": "AI Images and Design",
    "planTier": "Education invite",
    "subscriptionDuration": "1 year",
    "durationMonths": 12,
    "accessType": "Invite access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 year invite",
    "keyFeatures": "Design tools; education invite; 1 year",
    "shortDescription": "Canva Pro Edu invite with a one-year duration and PKR pricing.",
    "fullDescription": "Canva Pro Edu is listed as a distinct one-year invite plan. Confirm eligibility, availability, access method and delivery details before ordering.",
    "basePricePkr": 900,
    "sellingPricePkr": 900,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/canva-pro-edu-1-year.jpg",
    "imageAltText": "Canva Pro Edu — 1 Year Invite brand icon",
    "sourceProductUrl": "https://www.canva.com/education/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "CP",
    "guideUrl": "canva-pro-edu-1-year-pakistan/"
  },
  {
    "productId": "replit-core-40-credits",
    "sku": "ATP-REPLIT-CORE-40",
    "name": "Replit Core — $40 Credits",
    "sourceProductTitle": "Replit Core",
    "slug": "replit-core-40-credits",
    "category": "Development and Coding",
    "planTier": "Credit plan",
    "subscriptionDuration": "",
    "durationMonths": null,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "$40 credits",
    "keyFeatures": "Coding; app development; $40 credits",
    "shortDescription": "Replit Core credit plan with PKR pricing.",
    "fullDescription": "Replit Core is listed as a distinct $40 credit plan for coding and app-development workflows. Confirm current credit allocation, availability and delivery details before ordering.",
    "basePricePkr": 3200,
    "sellingPricePkr": 3200,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/replit-core-40-credits.png",
    "imageAltText": "Replit Core — $40 Credits brand icon",
    "sourceProductUrl": "https://replit.com/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "RC",
    "guideUrl": "replit-core-40-credits-pakistan/"
  },
  {
    "productId": "figma-pro-2-years-private",
    "sku": "ATP-FIGMA-PRO-2Y",
    "name": "Figma Pro — 2 Years Private",
    "sourceProductTitle": "Figma Pro",
    "slug": "figma-pro-2-years-private",
    "category": "Development and Coding",
    "planTier": "Pro plan",
    "subscriptionDuration": "2 years",
    "durationMonths": 24,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "2 years access",
    "keyFeatures": "Design collaboration; prototyping; 2 years",
    "shortDescription": "Figma Pro private plan with a two-year duration and PKR pricing.",
    "fullDescription": "Figma Pro is listed for a two-year private-access plan. Confirm current plan access, availability and delivery details before ordering.",
    "basePricePkr": 3000,
    "sellingPricePkr": 3000,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/figma-pro-2-years-private.png",
    "imageAltText": "Figma Pro — 2 Years Private brand icon",
    "sourceProductUrl": "https://www.figma.com/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "FP",
    "guideUrl": "figma-pro-2-years-private-pakistan/"
  },
  {
    "productId": "notion-business-3-months",
    "sku": "ATP-NOTION-BIZ-3M",
    "name": "Notion Business — 3 Months",
    "sourceProductTitle": "Notion Business",
    "slug": "notion-business-3-months",
    "category": "Productivity",
    "planTier": "Business plan",
    "subscriptionDuration": "3 months",
    "durationMonths": 3,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "3 months access",
    "keyFeatures": "Workspace; collaboration; 3 months",
    "shortDescription": "Notion Business plan with a three-month duration and PKR pricing.",
    "fullDescription": "Notion Business is listed for a three-month workspace and collaboration plan. Confirm current plan access, availability and delivery details before ordering.",
    "basePricePkr": 2200,
    "sellingPricePkr": 2200,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/notion-business-3-months.png",
    "imageAltText": "Notion Business — 3 Months brand icon",
    "sourceProductUrl": "https://www.notion.com/pricing",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "NB",
    "guideUrl": "notion-business-3-months-pakistan/"
  },
  {
    "productId": "chatgpt-plus-apple-account",
    "sku": "ATP-CHATGPT-APPLE",
    "name": "ChatGPT Plus — Apple Paid Account",
    "sourceProductTitle": "ChatGPT Plus",
    "slug": "chatgpt-plus-apple-account",
    "category": "AI Assistants",
    "planTier": "Apple paid account",
    "subscriptionDuration": "Confirm before ordering",
    "durationMonths": null,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "20-day warranty",
    "keyFeatures": "AI assistant; Apple paid account; 20-day warranty",
    "shortDescription": "ChatGPT Plus Apple paid account with PKR pricing and a stated 20-day warranty.",
    "fullDescription": "ChatGPT Plus Apple Paid Account is listed as a distinct option with a stated 20-day warranty. Confirm current availability, delivery method and warranty terms before ordering.",
    "basePricePkr": 2300,
    "sellingPricePkr": 2300,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/chatgpt-plus-apple-account.png",
    "imageAltText": "ChatGPT Plus — Apple Paid Account brand icon",
    "sourceProductUrl": "https://chatgpt.com/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "CP",
    "guideUrl": "chatgpt-plus-apple-account-pakistan/"
  },
  {
    "productId": "adobe-creative-2-months",
    "sku": "ATP-ADOBE-CREATIVE-2M",
    "name": "Adobe Creative — 2 Months",
    "sourceProductTitle": "Adobe Creative Cloud",
    "slug": "adobe-creative-2-months",
    "category": "AI Images and Design",
    "planTier": "Creative plan",
    "subscriptionDuration": "2 months",
    "durationMonths": 2,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "2 months access",
    "keyFeatures": "Creative tools; design; 2 months",
    "shortDescription": "Adobe Creative plan with a two-month duration and PKR pricing.",
    "fullDescription": "Adobe Creative is listed for buyers in Pakistan who need a two-month creative-tools plan. Confirm included applications, availability and delivery details before ordering.",
    "basePricePkr": 1700,
    "sellingPricePkr": 1700,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/adobe-creative-2-months.png",
    "imageAltText": "Adobe Creative — 2 Months brand icon",
    "sourceProductUrl": "https://www.adobe.com/creativecloud.html",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "AC",
    "guideUrl": "adobe-creative-2-months-pakistan/"
  },
  {
    "productId": "windows-11-pro-license-key",
    "sku": "ATP-WINDOWS11-PRO",
    "name": "Windows 11 Pro — Official License Key",
    "sourceProductTitle": "Windows 11 Pro",
    "slug": "windows-11-pro-license-key",
    "category": "Software",
    "planTier": "Pro license",
    "subscriptionDuration": "",
    "durationMonths": null,
    "accessType": "License key",
    "deliveryMethod": "WhatsApp delivery",
    "creditsOrUsageLimit": "License key",
    "keyFeatures": "Windows; Pro license key",
    "shortDescription": "Windows 11 Pro license key with PKR pricing.",
    "fullDescription": "Windows 11 Pro license key is listed with PKR pricing and WhatsApp delivery. Confirm current availability, activation terms and delivery details before ordering.",
    "basePricePkr": 1900,
    "sellingPricePkr": 1900,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/windows-11-pro-license-key.png",
    "imageAltText": "Windows 11 Pro — Official License Key brand icon",
    "sourceProductUrl": "https://www.microsoft.com/windows/windows-11",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "W1",
    "guideUrl": "windows-11-pro-license-key-pakistan/"
  },
  {
    "productId": "linkedin-premium-2-months",
    "sku": "ATP-LINKEDIN-PREM-2M",
    "name": "LinkedIn Premium — 2 Months",
    "sourceProductTitle": "LinkedIn Premium",
    "slug": "linkedin-premium-2-months",
    "category": "Productivity",
    "planTier": "Premium plan",
    "subscriptionDuration": "2 months",
    "durationMonths": 2,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "2 months access",
    "keyFeatures": "Career tools; professional networking; 2 months",
    "shortDescription": "LinkedIn Premium plan with a two-month duration and PKR pricing.",
    "fullDescription": "LinkedIn Premium is listed for a two-month professional-networking plan. Confirm current plan access, availability and delivery details before ordering.",
    "basePricePkr": 1500,
    "sellingPricePkr": 1500,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/linkedin-premium-2-months.png",
    "imageAltText": "LinkedIn Premium — 2 Months brand icon",
    "sourceProductUrl": "https://www.linkedin.com/premium/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "LP",
    "guideUrl": "linkedin-premium-2-months-pakistan/"
  },
  {
    "productId": "replit-core-1-year",
    "sku": "ATP-REPLIT-CORE-1Y",
    "name": "Replit Core — 1 Year",
    "sourceProductTitle": "Replit Core",
    "slug": "replit-core-1-year",
    "category": "Development and Coding",
    "planTier": "Core plan",
    "subscriptionDuration": "1 year",
    "durationMonths": 12,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 year access",
    "keyFeatures": "Coding; app development; 1 year",
    "shortDescription": "Replit Core plan with a one-year duration and PKR pricing.",
    "fullDescription": "Replit Core is listed as a distinct one-year coding and app-development plan. Confirm current plan access, availability and delivery details before ordering.",
    "basePricePkr": 12000,
    "sellingPricePkr": 12000,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/replit-core-1-year.png",
    "imageAltText": "Replit Core — 1 Year brand icon",
    "sourceProductUrl": "https://replit.com/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "RC",
    "guideUrl": "replit-core-1-year-pakistan/"
  },
  {
    "productId": "n8n-starter-1-year",
    "sku": "ATP-N8N-STARTER-1Y",
    "name": "n8n Starter — 1 Year",
    "sourceProductTitle": "n8n Starter",
    "slug": "n8n-starter-1-year",
    "category": "Automation",
    "planTier": "Starter plan",
    "subscriptionDuration": "1 year",
    "durationMonths": 12,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 year access",
    "keyFeatures": "Automation; workflows; 1 year",
    "shortDescription": "n8n Starter plan with a one-year duration and PKR pricing.",
    "fullDescription": "n8n Starter is listed for a one-year automation plan. Confirm current workflow limits, availability and delivery details before ordering.",
    "basePricePkr": 7000,
    "sellingPricePkr": 7000,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/n8n-starter-1-year.png",
    "imageAltText": "n8n Starter — 1 Year brand icon",
    "sourceProductUrl": "https://n8n.io/pricing/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "NS",
    "guideUrl": "n8n-starter-1-year-pakistan/"
  },
  {
    "productId": "manus-ai-pro-1-year",
    "sku": "ATP-MANUS-PRO-1Y",
    "name": "Manus AI Pro — 1 Year",
    "sourceProductTitle": "Manus AI Pro",
    "slug": "manus-ai-pro-1-year",
    "category": "AI Assistants",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 year",
    "durationMonths": 12,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 year access",
    "keyFeatures": "AI assistant; 1 year",
    "shortDescription": "Manus AI Pro plan with a one-year duration and PKR pricing.",
    "fullDescription": "Manus AI Pro is listed for a one-year AI assistant plan. Confirm current plan access, availability and delivery details before ordering.",
    "basePricePkr": 13000,
    "sellingPricePkr": 13000,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/manus-ai-pro-1-year.png",
    "imageAltText": "Manus AI Pro — 1 Year brand icon",
    "sourceProductUrl": "https://manus.im/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "MA",
    "guideUrl": "manus-ai-pro-1-year-pakistan/"
  },
  {
    "productId": "adobe-creative-1-year",
    "sku": "ATP-ADOBE-CREATIVE-1Y",
    "name": "Adobe Creative — 1 Year",
    "sourceProductTitle": "Adobe Creative Cloud",
    "slug": "adobe-creative-1-year",
    "category": "AI Images and Design",
    "planTier": "Creative plan",
    "subscriptionDuration": "1 year",
    "durationMonths": 12,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 year access",
    "keyFeatures": "Creative tools; design; 1 year",
    "shortDescription": "Adobe Creative plan with a one-year duration and PKR pricing.",
    "fullDescription": "Adobe Creative is listed for buyers in Pakistan who need a one-year creative-tools plan. Confirm included applications, availability and delivery details before ordering.",
    "basePricePkr": 25000,
    "sellingPricePkr": 25000,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/adobe-creative-1-year.png",
    "imageAltText": "Adobe Creative — 1 Year brand icon",
    "sourceProductUrl": "https://www.adobe.com/creativecloud.html",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "AC",
    "guideUrl": "adobe-creative-1-year-pakistan/"
  },
  {
    "productId": "gamma-pro-1-year",
    "sku": "ATP-GAMMA-PRO-1Y",
    "name": "Gamma Pro — 1 Year",
    "sourceProductTitle": "Gamma Pro",
    "slug": "gamma-pro-1-year",
    "category": "Productivity",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 year",
    "durationMonths": 12,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "1 year access",
    "keyFeatures": "Presentations; documents; 1 year",
    "shortDescription": "Gamma Pro plan with a one-year duration and PKR pricing.",
    "fullDescription": "Gamma Pro is listed for a one-year presentation and document-creation plan. Confirm current plan access, availability and delivery details before ordering.",
    "basePricePkr": 23000,
    "sellingPricePkr": 23000,
    "compareAtPricePkr": null,
    "discountPercent": null,
    "imageUrl": "/assets/product-icons/gamma-pro-1-year.jpg",
    "imageAltText": "Gamma Pro — 1 Year brand icon",
    "sourceProductUrl": "https://gamma.app/",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "GP",
    "guideUrl": "gamma-pro-1-year-pakistan/"
  },
  {
    "productId": "ideogram-ai-plus-private",
    "sku": "ATP-IDEOGRAM-AI",
    "name": "Ideogram AI Plus",
    "sourceProductTitle": "Ideogram AI Plus",
    "slug": "ideogram-ai-plus-private",
    "category": "AI Images and Design",
    "planTier": "Plus plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Shared / Private",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI image design tools",
    "keyFeatures": "AI images; text in images; design; creative assets",
    "shortDescription": "AI image design access for creative visual work.",
    "fullDescription": "Ideogram AI Plus is useful for image generation, creative graphics and text-focused AI image workflows with PKR pricing support.",
    "basePricePkr": 1500,
    "sellingPricePkr": 1500,
    "compareAtPricePkr": 5000,
    "discountPercent": 70,
    "imageUrl": "/assets/product-icons/ideogram-ai-plus-private.png",
    "imageAltText": "Ideogram AI Plus brand icon",
    "sourceProductUrl": "https://ideogram.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "IA",
    "guideUrl": "ideogram-ai-plus-pakistan/"
  },
  {
    "productId": "success-ai-starter-leads",
    "sku": "ATP-SUCCESS-AI",
    "name": "Success.ai Starter Leads",
    "sourceProductTitle": "Success.ai Starter",
    "slug": "success-ai-starter-leads",
    "category": "Marketing and Lead Generation",
    "planTier": "Starter leads",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "2,000 contacts",
    "keyFeatures": "Lead generation; outreach; email leads; sales workflow",
    "shortDescription": "Lead generation subscription for outreach and sales workflows.",
    "fullDescription": "Success.ai Starter Leads is listed for marketers and agencies that need lead generation and outreach workflow support with clear access terms.",
    "basePricePkr": 2400,
    "sellingPricePkr": 2400,
    "compareAtPricePkr": 3000,
    "discountPercent": 20,
    "imageUrl": "/assets/product-icons/success-ai-starter-leads.png",
    "imageAltText": "Success.ai Starter Leads brand icon",
    "sourceProductUrl": "https://success.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "SS",
    "guideUrl": "success-ai-starter-pakistan/"
  },
  {
    "productId": "vidiq",
    "sku": "ATP-VIDIQ",
    "name": "vidIQ",
    "sourceProductTitle": "vidIQ",
    "slug": "vidiq",
    "category": "Marketing and Lead Generation",
    "planTier": "YouTube growth plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "YouTube SEO tools",
    "keyFeatures": "YouTube SEO; keyword ideas; channel growth; content planning",
    "shortDescription": "YouTube growth and SEO tool for creators in Pakistan.",
    "fullDescription": "vidIQ helps YouTube creators research video ideas, improve titles and plan channel growth. Confirm current access details before ordering.",
    "basePricePkr": 2159,
    "sellingPricePkr": 2159,
    "compareAtPricePkr": 2600,
    "discountPercent": 17,
    "imageUrl": "/assets/product-icons/vidiq.png",
    "imageAltText": "vidIQ brand icon",
    "sourceProductUrl": "https://vidiq.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "V",
    "guideUrl": "vidiq-pakistan/"
  },
  {
    "productId": "playht",
    "sku": "ATP-PLAYHT",
    "name": "PlayHT",
    "sourceProductTitle": "PlayHT",
    "slug": "playht",
    "category": "AI Voice",
    "planTier": "Voice generation plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI voice generation",
    "keyFeatures": "AI voice; text to speech; narration; dubbing",
    "shortDescription": "AI voice generation tool for narration and audio content.",
    "fullDescription": "PlayHT is useful for creators and businesses that need text-to-speech, narration and AI voice workflows. Confirm usage limits and access before payment.",
    "basePricePkr": 3960,
    "sellingPricePkr": 3960,
    "compareAtPricePkr": 4800,
    "discountPercent": 18,
    "imageUrl": "/assets/product-icons/playht.png",
    "imageAltText": "PlayHT brand icon",
    "sourceProductUrl": "https://play.ht",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "P",
    "guideUrl": "playht-pakistan/"
  },
  {
    "productId": "wordai",
    "sku": "ATP-WORDAI",
    "name": "WordAI",
    "sourceProductTitle": "WordAI",
    "slug": "wordai",
    "category": "Writing and SEO",
    "planTier": "Writing plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Article rewriting tools",
    "keyFeatures": "Rewriting; article spinning; SEO writing; content refresh",
    "shortDescription": "AI rewriting tool for article and SEO content workflows.",
    "fullDescription": "WordAI is useful for rewriting and content-refresh workflows. Buyers should confirm access details, limits and use case suitability before ordering.",
    "basePricePkr": 600,
    "sellingPricePkr": 600,
    "compareAtPricePkr": 900,
    "discountPercent": 33,
    "imageUrl": "/assets/product-icons/wordai.png",
    "imageAltText": "WordAI brand icon",
    "sourceProductUrl": "https://wordai.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "W",
    "guideUrl": "wordai-pakistan/"
  },
  {
    "productId": "jasper-ai",
    "sku": "ATP-JASPER-AI",
    "name": "Jasper AI",
    "sourceProductTitle": "Jasper AI",
    "slug": "jasper-ai",
    "category": "Writing and SEO",
    "planTier": "AI copywriting plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI copywriting tools",
    "keyFeatures": "Copywriting; marketing content; brand voice; campaigns",
    "shortDescription": "AI copywriting tool for marketing and content workflows.",
    "fullDescription": "Jasper AI helps marketers, writers and agencies draft campaign copy, brand content and marketing ideas. Confirm plan limits and access before payment.",
    "basePricePkr": 600,
    "sellingPricePkr": 600,
    "compareAtPricePkr": 900,
    "discountPercent": 33,
    "imageUrl": "/assets/product-icons/jasper-ai.png",
    "imageAltText": "Jasper AI brand icon",
    "sourceProductUrl": "https://jasper.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "JA",
    "guideUrl": "jasper-ai-pakistan/"
  },
  {
    "productId": "hailuo-ai",
    "sku": "ATP-HAILUO-AI",
    "name": "Hailuo AI",
    "sourceProductTitle": "Hailuo AI",
    "slug": "hailuo-ai",
    "category": "AI Video",
    "planTier": "AI video plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI video generation",
    "keyFeatures": "AI video; prompts; creative clips; video generation",
    "shortDescription": "AI video generation tool for creator experiments and clips.",
    "fullDescription": "Hailuo AI is useful for AI video generation experiments, prompt-based creative clips and creator workflows. Confirm credits, limits and access before payment.",
    "basePricePkr": 2040,
    "sellingPricePkr": 2040,
    "compareAtPricePkr": 2800,
    "discountPercent": 27,
    "imageUrl": "/assets/product-icons/hailuo-ai.png",
    "imageAltText": "Hailuo AI brand icon",
    "sourceProductUrl": "https://hailuoai.video",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "HA",
    "guideUrl": "hailuo-ai-pakistan/"
  },
  {
    "productId": "dzine-master",
    "sku": "ATP-DZINE-MASTER",
    "name": "Dzine Master",
    "sourceProductTitle": "Dzine Master",
    "slug": "dzine-master",
    "category": "AI Images and Design",
    "planTier": "Master plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Full design suite",
    "keyFeatures": "AI design; image editing; creative tools; templates",
    "shortDescription": "AI-powered design suite for professional image creation and editing.",
    "fullDescription": "Dzine Master provides a complete AI design toolkit for creating professional graphics, editing images and accessing premium design templates and tools.",
    "basePricePkr": 5000,
    "sellingPricePkr": 5000,
    "compareAtPricePkr": 7000,
    "discountPercent": 29,
    "imageUrl": "/assets/product-icons/dzine-master.png",
    "imageAltText": "Dzine Master brand icon",
    "sourceProductUrl": "https://www.dzine.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "DM",
    "guideUrl": "dzine-master-pakistan/"
  },
  {
    "productId": "storyblocks-unlimited",
    "sku": "ATP-STORYBLOCKS",
    "name": "Storyblocks Unlimited",
    "sourceProductTitle": "Storyblocks Unlimited",
    "slug": "storyblocks-unlimited",
    "category": "AI Video",
    "planTier": "Unlimited plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Unlimited downloads",
    "keyFeatures": "Stock video; stock audio; templates; unlimited downloads; stock media (not AI generation)",
    "shortDescription": "Unlimited stock video, audio and template downloads for creators.",
    "fullDescription": "Storyblocks Unlimited gives access to a massive library of royalty-free stock video, audio, images and templates with unlimited downloads for content creation. Note: Storyblocks is a stock media library, not an AI video generator. It is different from AI tools such as Veo 3 or Runway ML that create video from text prompts. Use Storyblocks for ready-made clips, sound and templates to speed up editing; use an AI video generator when you need to create original footage from ideas.",
    "basePricePkr": 4000,
    "sellingPricePkr": 4000,
    "compareAtPricePkr": 6000,
    "discountPercent": 33,
    "imageUrl": "/assets/product-icons/storyblocks-unlimited.png",
    "imageAltText": "Storyblocks Unlimited brand icon",
    "sourceProductUrl": "https://www.storyblocks.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "SU",
    "guideUrl": "storyblocks-unlimited-pakistan/"
  },
  {
    "productId": "coursera-premium",
    "sku": "ATP-COURSERA",
    "name": "Coursera Premium",
    "sourceProductTitle": "Coursera Premium",
    "slug": "coursera-premium",
    "category": "Writing and SEO",
    "planTier": "Premium plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Full course access",
    "keyFeatures": "Online courses; certifications; learning; skill building",
    "shortDescription": "Premium access to Coursera courses and certifications.",
    "fullDescription": "Coursera Premium provides access to thousands of online courses, professional certifications and learning paths from top universities and companies.",
    "basePricePkr": 1000,
    "sellingPricePkr": 1000,
    "compareAtPricePkr": 1800,
    "discountPercent": 44,
    "imageUrl": "/assets/product-icons/coursera-premium.png",
    "imageAltText": "Coursera Premium brand icon",
    "sourceProductUrl": "https://www.coursera.org",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "CP",
    "guideUrl": "coursera-premium-pakistan/"
  },
  {
    "productId": "semrush-pro",
    "sku": "ATP-SEMRUSH-PRO",
    "name": "SEMrush Pro",
    "sourceProductTitle": "SEMrush Pro",
    "slug": "semrush-pro",
    "category": "Marketing and Lead Generation",
    "planTier": "Pro plan",
    "subscriptionDuration": "1 month",
    "durationMonths": 1,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "SEO and marketing tools",
    "keyFeatures": "SEO audit; keyword research; competitor analysis; backlink tracking",
    "shortDescription": "All-in-one SEO and marketing toolkit for keyword research and audits.",
    "fullDescription": "SEMrush Pro provides comprehensive SEO and digital marketing tools including keyword research, site audits, competitor analysis, backlink tracking and rank monitoring.",
    "basePricePkr": 1500,
    "sellingPricePkr": 1500,
    "compareAtPricePkr": 2500,
    "discountPercent": 40,
    "imageUrl": "/assets/product-icons/semrush-pro.png",
    "imageAltText": "SEMrush Pro brand icon",
    "sourceProductUrl": "https://www.semrush.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "SP",
    "guideUrl": "semrush-pro-pakistan/"
  }
];
