window.AI_TOOLS_PRODUCTS = [
  {
    "productId": "chatgpt-plus",
    "sku": "ATP-CHATGPT-PLUS",
    "name": "ChatGPT Plus",
    "sourceProductTitle": "ChatGPT Plus",
    "slug": "chatgpt-plus",
    "category": "AI Assistants",
    "planTier": "Plus plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Advanced AI assistant",
    "keyFeatures": "Writing; research; coding help; brainstorming",
    "shortDescription": "All-round AI assistant for writing, study, coding and business work.",
    "fullDescription": "ChatGPT Plus is useful for students, freelancers and teams that need one flexible assistant for daily writing, research, coding support and planning.",
    "basePricePkr": 1000,
    "sellingPricePkr": 1200,
    "compareAtPricePkr": 1500,
    "discountPercent": 20,
    "imageUrl": "https://www.google.com/s2/favicons?domain=chatgpt.com&sz=128",
    "imageAltText": "ChatGPT Plus subscription plan available in Pakistan",
    "sourceProductUrl": "https://chatgpt.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "CP",
    "guideUrl": "chatgpt-plus-pakistan/"
  },
  {
    "productId": "claude-ai",
    "sku": "ATP-CLAUDE-AI",
    "name": "Claude AI",
    "sourceProductTitle": "Claude Pro",
    "slug": "claude-ai",
    "category": "Development and Coding",
    "planTier": "AI assistant plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Writing and coding assistant",
    "keyFeatures": "Long writing; research; code review; summaries",
    "shortDescription": "Careful AI assistant for long writing, research and coding support.",
    "fullDescription": "Claude AI is suitable for students, writers and developers who need structured output, careful rewriting, long-document help and code explanation.",
    "basePricePkr": 1999,
    "sellingPricePkr": 2399,
    "compareAtPricePkr": 3000,
    "discountPercent": 20,
    "imageUrl": "https://www.google.com/s2/favicons?domain=claude.ai&sz=128",
    "imageAltText": "Claude AI subscription plan available in Pakistan",
    "sourceProductUrl": "https://claude.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "CA",
    "guideUrl": "claude-pro-pakistan/"
  },
  {
    "productId": "gemini-pro",
    "sku": "ATP-GEMINI-PRO",
    "name": "Gemini Pro",
    "sourceProductTitle": "Gemini Advanced",
    "slug": "gemini-pro",
    "category": "AI Assistants",
    "planTier": "Pro plan",
    "subscriptionDuration": "18 months",
    "durationMonths": 18,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Google AI access",
    "keyFeatures": "Google AI; writing; productivity; research",
    "shortDescription": "Google AI assistant access with long duration plan details.",
    "fullDescription": "Gemini Pro is listed for buyers who want Google AI access with PKR pricing, private access notes and WhatsApp order support in Pakistan.",
    "basePricePkr": 600,
    "sellingPricePkr": 720,
    "compareAtPricePkr": 999,
    "discountPercent": 28,
    "imageUrl": "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=128",
    "imageAltText": "Gemini Pro subscription plan available in Pakistan",
    "sourceProductUrl": "https://gemini.google.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "GP",
    "guideUrl": "gemini-pro-pakistan/"
  },
  {
    "productId": "elevenlabs-creator-private",
    "sku": "ATP-ELEVENLABS-CREATOR",
    "name": "ElevenLabs Creator - Private",
    "sourceProductTitle": "ElevenLabs Creator",
    "slug": "elevenlabs-creator-private",
    "category": "AI Voice",
    "planTier": "Creator plan",
    "subscriptionDuration": "3 months",
    "durationMonths": 3,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "300K+ credits",
    "keyFeatures": "AI voice; narration; dubbing; speech",
    "shortDescription": "AI voice subscription for narration, dubbing and creator audio workflows.",
    "fullDescription": "ElevenLabs Creator is useful for Pakistani creators who need AI voice generation, narration, dubbing and speech content with clear credit limits.",
    "basePricePkr": 2500,
    "sellingPricePkr": 3000,
    "compareAtPricePkr": 3600,
    "discountPercent": 17,
    "imageUrl": "https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=128",
    "imageAltText": "ElevenLabs Creator subscription plan available in Pakistan",
    "sourceProductUrl": "https://elevenlabs.io",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "EC",
    "guideUrl": "elevenlabs-creator-pakistan/"
  },
  {
    "productId": "runway-ml-unlimited-generations",
    "sku": "ATP-RUNWAY-ML",
    "name": "Runway ML - Unlimited Generations",
    "sourceProductTitle": "Runway ML",
    "slug": "runway-ml-unlimited-generations",
    "category": "AI Video",
    "planTier": "Video generation plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Video generation tools",
    "keyFeatures": "AI video; generation; editing; creative workflow",
    "shortDescription": "AI video generation access for creator and agency workflows.",
    "fullDescription": "Runway ML is listed for AI video generation buyers who need to confirm access type, delivery process, limits and PKR price before ordering.",
    "basePricePkr": 2100,
    "sellingPricePkr": 2520,
    "compareAtPricePkr": 3000,
    "discountPercent": 16,
    "imageUrl": "https://www.google.com/s2/favicons?domain=runwayml.com&sz=128",
    "imageAltText": "Runway ML subscription plan available in Pakistan",
    "sourceProductUrl": "https://runwayml.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "RM",
    "guideUrl": "runway-ml-pakistan/"
  },
  {
    "productId": "leonardo-ai",
    "sku": "ATP-LEONARDO-AI",
    "name": "Leonardo AI",
    "sourceProductTitle": "Leonardo AI",
    "slug": "leonardo-ai",
    "category": "AI Images and Design",
    "planTier": "Design plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Image generation tools",
    "keyFeatures": "AI images; design; creative assets; prompts",
    "shortDescription": "AI image and design subscription for creative visual workflows.",
    "fullDescription": "Leonardo AI helps designers and content creators make AI images, creative assets and visual experiments with clear access and pricing checks.",
    "basePricePkr": 1000,
    "sellingPricePkr": 1200,
    "compareAtPricePkr": 1500,
    "discountPercent": 20,
    "imageUrl": "https://www.google.com/s2/favicons?domain=leonardo.ai&sz=128",
    "imageAltText": "Leonardo AI subscription plan available in Pakistan",
    "sourceProductUrl": "https://leonardo.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "LA",
    "guideUrl": "leonardo-ai-pakistan/"
  },
  {
    "productId": "grammarly-pro",
    "sku": "ATP-GRAMMARLY-PRO",
    "name": "Grammarly Pro",
    "sourceProductTitle": "Grammarly Pro",
    "slug": "grammarly-pro",
    "category": "Writing and SEO",
    "planTier": "Pro plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Grammar and writing tools",
    "keyFeatures": "Grammar; rewriting; proofreading; writing clarity",
    "shortDescription": "Writing assistant for grammar, rewriting and clarity checks.",
    "fullDescription": "Grammarly Pro is useful for students, writers and freelancers who want grammar checking, proofreading, rewriting suggestions and clearer English output.",
    "basePricePkr": 799,
    "sellingPricePkr": 959,
    "compareAtPricePkr": 1200,
    "discountPercent": 20,
    "imageUrl": "https://www.google.com/s2/favicons?domain=grammarly.com&sz=128",
    "imageAltText": "Grammarly Pro subscription plan available in Pakistan",
    "sourceProductUrl": "https://grammarly.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "GP",
    "guideUrl": "grammarly-premium-pakistan/"
  },
  {
    "productId": "quillbot",
    "sku": "ATP-QUILLBOT",
    "name": "QuillBot",
    "sourceProductTitle": "QuillBot",
    "slug": "quillbot",
    "category": "Writing and SEO",
    "planTier": "Writing plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Paraphrasing and writing tools",
    "keyFeatures": "Paraphrasing; summarizing; grammar; writing workflow",
    "shortDescription": "Paraphrasing and writing support for students and freelancers.",
    "fullDescription": "QuillBot helps with paraphrasing, rewriting, summaries and grammar workflows for buyers who need affordable writing support.",
    "basePricePkr": 399,
    "sellingPricePkr": 479,
    "compareAtPricePkr": 700,
    "discountPercent": 31,
    "imageUrl": "https://www.google.com/s2/favicons?domain=quillbot.com&sz=128",
    "imageAltText": "QuillBot subscription plan available in Pakistan",
    "sourceProductUrl": "https://quillbot.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "Q",
    "guideUrl": "quillbot-premium-pakistan/"
  },
  {
    "productId": "lovable-ai-pro-private",
    "sku": "ATP-LOVABLE-AI-PRO",
    "name": "Lovable AI Pro - Private",
    "sourceProductTitle": "Lovable AI Pro",
    "slug": "lovable-ai-pro-private",
    "category": "Development and Coding",
    "planTier": "Pro plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Monthly and daily credits",
    "keyFeatures": "AI coding; app building; prototyping; development",
    "shortDescription": "AI coding and app-building subscription for fast prototypes.",
    "fullDescription": "Lovable AI Pro is useful for builders and developers who want AI-assisted app creation, prototyping and coding workflow support.",
    "basePricePkr": 1370,
    "sellingPricePkr": 1644,
    "compareAtPricePkr": 2000,
    "discountPercent": 18,
    "imageUrl": "https://www.google.com/s2/favicons?domain=lovable.dev&sz=128",
    "imageAltText": "Lovable AI Pro subscription plan available in Pakistan",
    "sourceProductUrl": "https://lovable.dev",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "LA",
    "guideUrl": "lovable-ai-pro-pakistan/"
  },
  {
    "productId": "heygen-ai",
    "sku": "ATP-HEYGEN-AI",
    "name": "HeyGen AI",
    "sourceProductTitle": "HeyGen AI",
    "slug": "heygen-ai",
    "category": "AI Video",
    "planTier": "Video plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Avatars and text-to-video",
    "keyFeatures": "AI avatars; text to video; presentations; creator video",
    "shortDescription": "AI avatar and text-to-video tool for creator workflows.",
    "fullDescription": "HeyGen AI is listed for buyers who need avatar videos, text-to-video workflows and creator-friendly video production support.",
    "basePricePkr": 1500,
    "sellingPricePkr": 1800,
    "compareAtPricePkr": 2200,
    "discountPercent": 18,
    "imageUrl": "https://www.google.com/s2/favicons?domain=heygen.com&sz=128",
    "imageAltText": "HeyGen AI subscription plan available in Pakistan",
    "sourceProductUrl": "https://heygen.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "HA",
    "guideUrl": "heygen-ai-pakistan/"
  },
  {
    "productId": "ideogram-ai-plus-private",
    "sku": "ATP-IDEOGRAM-AI",
    "name": "Ideogram AI Plus - Private",
    "sourceProductTitle": "Ideogram AI Plus",
    "slug": "ideogram-ai-plus-private",
    "category": "AI Images and Design",
    "planTier": "Plus plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI image design tools",
    "keyFeatures": "AI images; text in images; design; creative assets",
    "shortDescription": "AI image design access for creative visual work.",
    "fullDescription": "Ideogram AI Plus is useful for image generation, creative graphics and text-focused AI image workflows with PKR pricing support.",
    "basePricePkr": 3500,
    "sellingPricePkr": 4200,
    "compareAtPricePkr": 5000,
    "discountPercent": 16,
    "imageUrl": "https://www.google.com/s2/favicons?domain=ideogram.ai&sz=128",
    "imageAltText": "Ideogram AI Plus subscription plan available in Pakistan",
    "sourceProductUrl": "https://ideogram.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "IA",
    "guideUrl": "ideogram-ai-plus-pakistan/"
  },
  {
    "productId": "success-ai-starter-leads",
    "sku": "ATP-SUCCESS-AI",
    "name": "Success.ai Starter Leads",
    "sourceProductTitle": "Success.ai Starter",
    "slug": "success-ai-starter-leads",
    "category": "Marketing and Lead Generation",
    "planTier": "Starter leads",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "2,000 contacts",
    "keyFeatures": "Lead generation; outreach; email leads; sales workflow",
    "shortDescription": "Lead generation subscription for outreach and sales workflows.",
    "fullDescription": "Success.ai Starter Leads is listed for marketers and agencies that need lead generation and outreach workflow support with clear access terms.",
    "basePricePkr": 2000,
    "sellingPricePkr": 2400,
    "compareAtPricePkr": 3000,
    "discountPercent": 20,
    "imageUrl": "https://www.google.com/s2/favicons?domain=success.ai&sz=128",
    "imageAltText": "Success.ai Starter Leads subscription plan available in Pakistan",
    "sourceProductUrl": "https://success.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Verified",
    "requiresSupplierConfirmation": false,
    "initials": "SS",
    "guideUrl": "success-ai-starter-pakistan/"
  },
  {
    "productId": "vidiq",
    "sku": "ATP-VIDIQ",
    "name": "vidIQ",
    "sourceProductTitle": "vidIQ",
    "slug": "vidiq",
    "category": "Marketing and Lead Generation",
    "planTier": "YouTube growth plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "YouTube SEO tools",
    "keyFeatures": "YouTube SEO; keyword ideas; channel growth; content planning",
    "shortDescription": "YouTube growth and SEO tool for creators in Pakistan.",
    "fullDescription": "vidIQ helps YouTube creators research video ideas, improve titles and plan channel growth. Confirm current access details before ordering.",
    "basePricePkr": 1799,
    "sellingPricePkr": 2159,
    "compareAtPricePkr": 2600,
    "discountPercent": 17,
    "imageUrl": "https://www.google.com/s2/favicons?domain=vidiq.com&sz=128",
    "imageAltText": "vidIQ subscription plan available in Pakistan",
    "sourceProductUrl": "https://vidiq.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "V",
    "guideUrl": "vidiq-pakistan/"
  },
  {
    "productId": "playht",
    "sku": "ATP-PLAYHT",
    "name": "PlayHT",
    "sourceProductTitle": "PlayHT",
    "slug": "playht",
    "category": "AI Voice",
    "planTier": "Voice generation plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI voice generation",
    "keyFeatures": "AI voice; text to speech; narration; dubbing",
    "shortDescription": "AI voice generation tool for narration and audio content.",
    "fullDescription": "PlayHT is useful for creators and businesses that need text-to-speech, narration and AI voice workflows. Confirm usage limits and access before payment.",
    "basePricePkr": 3300,
    "sellingPricePkr": 3960,
    "compareAtPricePkr": 4800,
    "discountPercent": 18,
    "imageUrl": "https://www.google.com/s2/favicons?domain=play.ht&sz=128",
    "imageAltText": "PlayHT subscription plan available in Pakistan",
    "sourceProductUrl": "https://play.ht",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "P",
    "guideUrl": "playht-pakistan/"
  },
  {
    "productId": "supergrok",
    "sku": "ATP-SUPERGROK",
    "name": "SuperGrok",
    "sourceProductTitle": "SuperGrok",
    "slug": "supergrok",
    "category": "AI Assistants",
    "planTier": "SuperGrok plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Advanced Grok access",
    "keyFeatures": "AI assistant; research; social workflows; current topics",
    "shortDescription": "Grok assistant access for current-topic and social workflows.",
    "fullDescription": "SuperGrok is listed for buyers comparing advanced AI assistants for research, current-topic workflows and productivity. Confirm platform requirements before payment.",
    "basePricePkr": 1500,
    "sellingPricePkr": 1800,
    "compareAtPricePkr": 2400,
    "discountPercent": 25,
    "imageUrl": "https://www.google.com/s2/favicons?domain=x.ai&sz=128",
    "imageAltText": "SuperGrok subscription plan available in Pakistan",
    "sourceProductUrl": "https://x.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "S",
    "guideUrl": "supergrok-pakistan/"
  },
  {
    "productId": "wordai",
    "sku": "ATP-WORDAI",
    "name": "WordAI",
    "sourceProductTitle": "WordAI",
    "slug": "wordai",
    "category": "Writing and SEO",
    "planTier": "Writing plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Article rewriting tools",
    "keyFeatures": "Rewriting; article spinning; SEO writing; content refresh",
    "shortDescription": "AI rewriting tool for article and SEO content workflows.",
    "fullDescription": "WordAI is useful for rewriting and content-refresh workflows. Buyers should confirm access details, limits and use case suitability before ordering.",
    "basePricePkr": 500,
    "sellingPricePkr": 600,
    "compareAtPricePkr": 900,
    "discountPercent": 33,
    "imageUrl": "https://www.google.com/s2/favicons?domain=wordai.com&sz=128",
    "imageAltText": "WordAI subscription plan available in Pakistan",
    "sourceProductUrl": "https://wordai.com",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "W",
    "guideUrl": "wordai-pakistan/"
  },
  {
    "productId": "jasper-ai",
    "sku": "ATP-JASPER-AI",
    "name": "Jasper AI",
    "sourceProductTitle": "Jasper AI",
    "slug": "jasper-ai",
    "category": "Writing and SEO",
    "planTier": "AI copywriting plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI copywriting tools",
    "keyFeatures": "Copywriting; marketing content; brand voice; campaigns",
    "shortDescription": "AI copywriting tool for marketing and content workflows.",
    "fullDescription": "Jasper AI helps marketers, writers and agencies draft campaign copy, brand content and marketing ideas. Confirm plan limits and access before payment.",
    "basePricePkr": 500,
    "sellingPricePkr": 600,
    "compareAtPricePkr": 900,
    "discountPercent": 33,
    "imageUrl": "https://www.google.com/s2/favicons?domain=jasper.ai&sz=128",
    "imageAltText": "Jasper AI subscription plan available in Pakistan",
    "sourceProductUrl": "https://jasper.ai",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "JA",
    "guideUrl": "jasper-ai-pakistan/"
  },
  {
    "productId": "google-ai-ultra-plan",
    "sku": "ATP-GOOGLE-AI-ULTRA",
    "name": "Google AI Ultra Plan",
    "sourceProductTitle": "Google AI Ultra",
    "slug": "google-ai-ultra-plan",
    "category": "AI Assistants",
    "planTier": "Ultra plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "Google AI Ultra access",
    "keyFeatures": "Google AI; advanced models; productivity; research",
    "shortDescription": "Google AI Ultra access for advanced Google AI workflows.",
    "fullDescription": "Google AI Ultra Plan is listed for buyers who want advanced Google AI access. Confirm current availability, access method and limits before ordering.",
    "basePricePkr": 1470,
    "sellingPricePkr": 1764,
    "compareAtPricePkr": 2400,
    "discountPercent": 27,
    "imageUrl": "https://www.google.com/s2/favicons?domain=one.google.com&sz=128",
    "imageAltText": "Google AI Ultra Plan subscription available in Pakistan",
    "sourceProductUrl": "https://one.google.com/about/google-ai-plans",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "GA",
    "guideUrl": "google-ai-ultra-pakistan/"
  },
  {
    "productId": "hailuo-ai",
    "sku": "ATP-HAILUO-AI",
    "name": "Hailuo AI",
    "sourceProductTitle": "Hailuo AI",
    "slug": "hailuo-ai",
    "category": "AI Video",
    "planTier": "AI video plan",
    "subscriptionDuration": "Flexible plan",
    "durationMonths": 0,
    "accessType": "Private access",
    "deliveryMethod": "WhatsApp activation",
    "creditsOrUsageLimit": "AI video generation",
    "keyFeatures": "AI video; prompts; creative clips; video generation",
    "shortDescription": "AI video generation tool for creator experiments and clips.",
    "fullDescription": "Hailuo AI is useful for AI video generation experiments, prompt-based creative clips and creator workflows. Confirm credits, limits and access before payment.",
    "basePricePkr": 1700,
    "sellingPricePkr": 2040,
    "compareAtPricePkr": 2800,
    "discountPercent": 27,
    "imageUrl": "https://www.google.com/s2/favicons?domain=hailuoai.video&sz=128",
    "imageAltText": "Hailuo AI subscription plan available in Pakistan",
    "sourceProductUrl": "https://hailuoai.video",
    "sourceRatingCount": 0,
    "dataVerificationStatus": "Confirm before ordering",
    "requiresSupplierConfirmation": true,
    "initials": "HA",
    "guideUrl": "hailuo-ai-pakistan/"
  }
];
